import { describe, expect, it, vi } from "vitest";
import { createController } from "./controller";
function setup(){let accept:(key:unknown,balance:boolean)=>boolean=()=>false;let state:any,menu:any[]=[];const runner={start:vi.fn(async()=>({status:"completed",attempts:2,reservedNanoUsd:1e9,upperNanoUsd:108000,costNanoUsd:54000,usage:[]})),cancel:vi.fn()};const show=vi.fn(async()=>({response:1}));let resolveProfile:(id:string)=>any=()=>undefined;
 const createRunner=vi.fn((resolve:any)=>{resolveProfile=resolve;return runner;});const close=vi.fn();const controller=createController({openForm:fn=>{accept=fn;},closeForm:close,createRunner,show,setMenu:m=>{menu=m;},writeState:s=>{state=s;},quit:vi.fn()});controller.install();return {controller,prepare:(k:unknown,b=true)=>accept(k,b),getState:()=>state,getMenu:()=>menu,runner,createRunner,show,close,profile:(id:string)=>resolveProfile(id)};}
describe("user-only OpenRouter preparation and native sending",()=>{
 it("starts empty; preparation only stores an isolated profile with zero runner creation",()=>{const t=setup();expect(t.getState().prepared).toBe(false);t.controller.configure();expect(t.prepare("SYNTHETIC-ONLY-KEY",false)).toBe(false);expect(t.prepare("bad")).toBe(false);expect(t.prepare("SYNTHETIC-ONLY-KEY")).toBe(true);expect(t.getState().prepared).toBe(true);expect(t.createRunner).not.toHaveBeenCalled();expect(t.runner.start).not.toHaveBeenCalled();expect(JSON.stringify(t.getState())).not.toContain("SYNTHETIC");expect(t.prepare("SYNTHETIC-SECOND-KEY")).toBe(false);});
 it("requires native confirmation; rejection clears key and cannot retry",async()=>{const t=setup();t.controller.configure();t.prepare("SYNTHETIC-ONLY-KEY");await t.controller.send();expect(t.show).toHaveBeenCalledOnce();expect(t.createRunner).not.toHaveBeenCalled();expect(t.getState().prepared).toBe(false);await t.controller.send();expect(t.show).toHaveBeenCalledOnce();});
 it("coalesces native clicks, emits only numeric receipt, clears key and stops",async()=>{const t=setup();t.show.mockResolvedValue({response:0});t.controller.configure();t.prepare("SYNTHETIC-ONLY-KEY");const a=t.controller.send(),b=t.controller.send();expect(a).toBe(b);await a;expect(t.runner.start).toHaveBeenCalledOnce();expect(t.createRunner).toHaveBeenCalledOnce();expect(t.getState()).toMatchObject({phase:"finished",prepared:false,receipt:{status:"completed",attempts:2}});expect(t.profile(t.runner.start.mock.calls[0][0])).toBeUndefined();expect(JSON.stringify(t.getState())).not.toContain("SYNTHETIC");});
 it("cancel during confirmation never constructs or sends a runner",async()=>{const t=setup();let release!:(v:any)=>void;t.show.mockImplementation(()=>new Promise(r=>{release=r;}));t.controller.configure();t.prepare("SYNTHETIC-ONLY-KEY");const sending=t.controller.send();await Promise.resolve();t.controller.cancel();release({response:0});await sending;expect(t.createRunner).not.toHaveBeenCalled();expect(t.getState().prepared).toBe(false);});
 it("cancel before preparation permanently blocks later submission",()=>{const t=setup();t.controller.configure();t.controller.cancel();expect(t.prepare("SYNTHETIC-ONLY-KEY")).toBe(false);expect(t.getState()).toMatchObject({phase:"cancelled",prepared:false});});
});
