import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {afterEach,afterAll,expect,it,vi} from 'vitest';
import {contextFixture} from '../../../scripts/verify/memory-context/context-fixture';
import {ConversationTranscriptStore} from '../orchestrator/conversation-transcript-store';import {createTranscriptSink} from '../orchestrator/transcript-sink';
import {createMainHistory,readHistoryEvidence,claimHistoryResponseEvidence} from '../memory-history/main-history';import {createNativeHistoryProvider} from '../memory-sources/native-history-provider';
import {createMainSourceProvider} from '../memory-sources/main-source-provider';
import {initializeStorageContext} from '../storage-context';import {resolveRuntimeProfile} from '../runtime-profile';
import {createConversationTranscriptAdapter} from './conversation-transcript-adapter';import {createMainSRuntimePort} from './main-s-runtime-port';
import {createMainResponsesBinding,createMainResponsesLimits} from './main-responses-binding';import {setVendorRuntimeSettingsGetter} from '../orchestrator/vendors/runtime-settings';
vi.mock('electron',()=>({app:{getPath:()=>{throw Error('PRODUCTION_FORBIDDEN')}}}));
const isolation=fs.mkdtempSync(path.join(os.tmpdir(),'smh-native-stream-'));
const storage=initializeStorageContext(resolveRuntimeProfile({argv:['--firefly-profile=test','--firefly-isolation-root='+isolation],env:{},isPackaged:false,productionAppData:path.join(os.tmpdir(),'smh-unopened-production')}));
afterEach(()=>{vi.restoreAllMocks();setVendorRuntimeSettingsGetter(()=>({}));fs.rmSync(path.join(storage.dataRoot,'transcripts'),{recursive:true,force:true})});afterAll(()=>fs.rmSync(isolation,{recursive:true,force:true}));
const events=()=>{const item={id:'msg',type:'message',role:'assistant',status:'completed',content:[{type:'output_text',text:'synthetic answer',annotations:[]}]};return [{type:'response.created',response:{id:'resp',status:'in_progress',output:[]}},{type:'response.output_item.added',output_index:0,item:{...item,status:'in_progress',content:[]}},{type:'response.content_part.added',item_id:'msg',output_index:0,content_index:0,part:{type:'output_text',text:'',annotations:[]}},{type:'response.output_text.delta',item_id:'msg',output_index:0,content_index:0,delta:'synthetic answer'},{type:'response.output_text.done',item_id:'msg',output_index:0,content_index:0,text:'synthetic answer'},{type:'response.content_part.done',item_id:'msg',output_index:0,content_index:0,part:item.content[0]},{type:'response.output_item.done',output_index:0,item},{type:'response.completed',response:{id:'resp',status:'completed',output:[item]}}].map((e,sequence_number)=>({...e,sequence_number}))};
async function fixture(selected=true,multiple=false){
 const f=await contextFixture(),store=new ConversationTranscriptStore(storage.dataRoot);await store.append('session-a',{id:'old-user',kind:'user',turnId:'old-turn',revision:1,payload:{text:'harbor coffee'},at:1000});await store.append('session-a',{id:'current-user',kind:'user',turnId:'current-turn',revision:1,payload:{text:'new question'},at:2000});await store.checkpoint('session-a');
 let held=0,reads=0,starts=0,sends=0;let onStream:undefined|(()=>Promise<void>),afterAssistant:undefined|(()=>Promise<void>),failRelease=false,snapshotIdentity='bbbbbbbbbbbbbbbb';const observed:any[]=[];
 const transport={...f.transport,historyCommand:async(c:any)=>f.repo.historyCommand(c)};const history=createMainHistory({actorAuthority:f.actorAuthority,registry:f.registry,transport});
 const native=createNativeHistoryProvider({actorAuthority:f.actorAuthority,actorToken:f.actor,store,history,deadlineMs:1000,endpointFactory:async()=>{starts++;let acquired=false,disposed=false;return {rootIdentity:{volumeSerial:42,fileIndex:'1111111111111111'},async read(parts,max){reads++;const bytes=fs.readFileSync(path.join(storage.dataRoot,'transcripts',...parts));if(bytes.length>max)throw Error('budget');acquired=true;held++;return {identity:{volumeSerial:42,fileIndex:parts[1]==='snapshot.json'?snapshotIdentity:'aaaaaaaaaaaaaaaa'},bytes}},assertLive(){if(disposed)throw Error('dead')},async dispose(){if(acquired&&!disposed)held--;disposed=true;if(failRelease)throw Error('SYNTHETIC_CLEANUP_FAILURE')}}}});
 await native.capture();const old=await native.query({query:'harbor'});if(old.status!=='queried')throw Error('query failed');
 setVendorRuntimeSettingsGetter(()=>({}));const client:any={baseURL:'https://api.openai.com/v1',maxRetries:0,logLevel:'off',logger:{},fetch:()=>{throw Error('NETWORK_FORBIDDEN')},responses:{inputTokens:{count:async()=>({object:'response.input_tokens',input_tokens:40})},create:async()=>{sends++;return {async *[Symbol.asyncIterator](){await onStream?.();for(const e of events())yield e}}}}};Object.assign(client.responses,{_client:client});Object.assign(client.responses.inputTokens,{_client:client});
 const binding=createMainResponsesBinding({enabled:true,client,limits:createMainResponsesLimits({model:'fixture-model',limitsSource:'fixture://native-stream',modelMaxOutputTokens:512,budget:{maxContextTokens:30000,reservedOutputTokens:128,safetyMarginTokens:16,maxSTokens:4000,minRecentCompleteTurns:1}}),configuration:()=>({revision:1,config:{provider:'ChatGPT（OpenAI）',baseUrl:'https://api.openai.com/v1',model:'fixture-model',explicitTransport:'responses'}})})!;
 let adapter:any,runtimeContext:any;const port=createMainSRuntimePort({enabled:true,clock:f.options.clock,registry:f.registry,transport,actorAuthority:f.actorAuthority,actorToken:f.actor,binding,history:{query:async()=>{if(!selected)return [];const q=await native.query({query:'harbor'});if(q.status!=='queried')throw Error('MEMORY_HISTORY_COVERAGE_INSUFFICIENT');if(multiple){const other=await native.query({query:"harbor"});if(other.status!=="queried")throw Error("query failed");return [q.result.evidence,other.result.evidence]}return [q.result.evidence]}},createTranscript:context=>(runtimeContext=context,adapter=createConversationTranscriptAdapter({enabled:true,store,context,actorAuthority:f.actorAuthority,actorToken:f.actor,beforeMutation:(kind,entry,ticket)=>native.beforeMutation(kind,entry,ticket)})!)})!;
 const sink=createTranscriptSink({store,conversationId:'session-a',runId:'run',assistantTurnId:'assistant'}),input={request:{model:'fixture-model',messages:[{role:'system' as const,content:'fixed'}],maxTokens:128,stream:true},stream:{conversationId:'session-a',runId:'run',userTurnId:'current-turn',assistantTurnId:'assistant',sink,onEvent:(e:any)=>observed.push(e),isCurrent:()=>true}};
 const append=fs.promises.appendFile.bind(fs.promises);vi.spyOn(fs.promises,'appendFile').mockImplementation(async(...args:any[])=>{expect(held).toBe(0);expect(()=>readHistoryEvidence(f.actorAuthority,f.actor,old.result.evidence)).toThrow();const result=await (append as any)(...args);if(String(args[1]).includes('"kind":"assistant"'))await afterAssistant?.();return result});
 return {...f,store,history,native,port,input,old,observed,runtimeContext,setStreamHook:(hook:typeof onStream)=>{onStream=hook},setAfterAssistant:(hook:typeof afterAssistant)=>{afterAssistant=hook},failCleanup:()=>{failRelease=true},replaceSnapshotIdentity:()=>{snapshotIdentity='cccccccccccccccc'},get reads(){return reads},get starts(){return starts},get sends(){return sends},close:async()=>{await adapter.close();await native.close()}};
}
it('S with no selected H persists normally but revokes and settles all preexisting native H heads before write',async()=>{
 const f=await fixture(false);try{expect((await f.port.run(f.input)).status).toBe('sent');const entries=(await f.store.read('session-a')).entries;expect(entries.filter(e=>e.kind==='assistant')).toHaveLength(1);expect(entries.filter(e=>e.kind==='assistant_settlement'&&e.payload.result==='success')).toHaveLength(1);const snapshot=(f.commands as any[]).findLast(c=>c.kind==='snapshot');expect(snapshot.body.historyDeps).toEqual([]);for(const c of (f.commands as any[]).filter(c=>c.body.responseProgress))expect(c.body.responseProgress.expectedRefs.every((r:any)=>!r.headId.startsWith('history-transcript-'))).toBe(true);expect(f.sends).toBe(1)}finally{await f.close()}
});
it('selected native H uses held ticket and exact pending response union for assistant and success then fresh recapture',async()=>{
 const f=await fixture();try{expect((await f.port.run(f.input)).status).toBe('sent');const entries=(await f.store.read('session-a')).entries;expect(entries.filter(e=>e.kind==='assistant')).toHaveLength(1);expect(entries.filter(e=>e.kind==='assistant_settlement'&&e.payload.result==='success')).toHaveLength(1);expect(f.reads).toBeGreaterThan(8);expect(f.sends).toBe(1);const progress=(f.commands as any[]).filter(c=>c.body.responseProgress);expect(progress.some(c=>c.body.responseProgress.expectedRefs.some((r:any)=>r.headId.startsWith('history-transcript-')))).toBe(true);await f.native.capture();expect((await f.native.query({query:'harbor'})).status).toBe('queried');expect(()=>readHistoryEvidence(f.actorAuthority,f.actor,f.old.result.evidence)).toThrow()}finally{await f.close()}
},10000);

it('two selected evidence caps from the same native factory share one response witness and exact union',async()=>{const f=await fixture(true,true);try{expect((await f.port.run(f.input)).status).toBe('sent');expect((await f.store.read('session-a')).entries.filter(e=>e.kind==='assistant_settlement'&&e.payload.result==='success')).toHaveLength(1)}finally{await f.close()}},10000);

it.each(['cancel','close','forget','remove','snapshot-replace','prefix-edit','extra-append','rewind'] as const)('selected H %s during streaming prevents canonical assistant and success',async kind=>{
 const f=await fixture(),controller=new AbortController();let changed=false;
 f.setStreamHook(async()=>{changed=true;if(kind==='cancel')controller.abort();else if(kind==='close')await f.native.close();else if(kind==='forget')await f.native.invalidate('forget');else if(kind==='remove'){const hit=f.old.result.hits[0];await f.history.remove(f.actor,{documentId:hit.document.id,revision:hit.document.revision})}else if(kind==='extra-append')await f.store.append('session-a',{id:'extra',kind:'user',turnId:'extra',revision:1,payload:{text:'extra synthetic'}});else if(kind==='rewind')await f.store.append('session-a',{id:'rewind',kind:'turn_rewind',payload:{anchorUserTurnId:'current-turn',disposition:'keep_user',reason:'regenerate'}});else{const leaf=kind==='snapshot-replace'?'snapshot.json':'transcript.jsonl',p=path.join(storage.dataRoot,'transcripts','session-a',leaf);fs.writeFileSync(p,fs.readFileSync(p,'utf8').replace('harbor coffee','edited coffee'))}});
 try{await expect(f.port.run({...f.input,signal:controller.signal})).rejects.toThrow();expect(changed).toBe(true);const entries=(await f.store.read('session-a')).entries;expect(entries.some(e=>e.kind==='assistant')).toBe(false);expect(entries.some(e=>e.kind==='assistant_settlement'&&e.payload.result==='success')).toBe(false);expect(f.observed.some(e=>e.type==='text_message_end')).toBe(false);expect(f.sends).toBe(1)}finally{await f.close()}
},10000);
it.each(['prefix-edit','snapshot-replace','extra-append','cleanup-failure','cancel'] as const)('selected H %s after own assistant burns continuation and never settles success',async kind=>{
 const f=await fixture(),controller=new AbortController();f.setAfterAssistant(async()=>{if(kind==='cancel')controller.abort();else if(kind==='cleanup-failure')f.failCleanup();else {const leaf=kind==='snapshot-replace'?'snapshot.json':'transcript.jsonl',p=path.join(storage.dataRoot,'transcripts','session-a',leaf);if(kind==='extra-append')fs.appendFileSync(p,JSON.stringify({id:'external',seq:4,at:2001,kind:'user',turnId:'external',revision:1,payload:{text:'external synthetic'}})+'\n');else fs.writeFileSync(p,fs.readFileSync(p,'utf8').replace('harbor coffee','edited coffee'))}});
 try{await expect(f.port.run({...f.input,signal:controller.signal})).rejects.toThrow();const entries=(await f.store.read('session-a')).entries;expect(entries.some(e=>e.kind==='assistant_settlement'&&e.payload.result==='success')).toBe(false);expect(f.observed.some(e=>e.type==='text_message_end')).toBe(false);expect(()=>readHistoryEvidence(f.actorAuthority,f.actor,f.old.result.evidence)).toThrow()}finally{await f.close().catch(()=>{})}
},10000);
it.each(['cloned-cap','cloned-ticket','foreign-actor'] as const)('response %s cannot authorize a held acquisition or write',async kind=>{
 const f=await fixture(),original=f.runtimeContext.validateHistoryResponseStep;
 vi.spyOn(f.runtimeContext,'validateHistoryResponseStep').mockImplementation((token:any,cap:any,ticket:any,signal:any)=>original(kind==='foreign-actor'?{}:token,kind==='cloned-cap'?{...cap}:cap,kind==='cloned-ticket'?{...ticket}:ticket,signal));
 try{await expect(f.port.run(f.input)).rejects.toThrow();expect((await f.store.read('session-a')).entries.some(e=>e.kind==='assistant')).toBe(false)}finally{await f.close()}
},10000);

it('same session ID from another provider never enters current-owner response pending refs',async()=>{
 const f=await fixture(),adapter=createMainSourceProvider({providerId:'other',authorize:()=>true,withLease:async(_id,run)=>run(async()=>{throw Error('UNUSED_SOURCE')})}),otherActor=f.actorAuthority.bindActor(f.access,adapter,{providerId:'other',sessionId:'session-a',messageId:'binding'});
 const other=createNativeHistoryProvider({actorAuthority:f.actorAuthority,actorToken:otherActor,history:f.history,store:f.store,deadlineMs:1000,endpointFactory:async()=>({rootIdentity:{volumeSerial:42,fileIndex:'1111111111111111'},async read(parts){return {identity:{volumeSerial:42,fileIndex:parts[1]==='snapshot.json'?'bbbbbbbbbbbbbbbb':'aaaaaaaaaaaaaaaa'},bytes:fs.readFileSync(path.join(storage.dataRoot,'transcripts',...parts))}},assertLive(){},async dispose(){}})});
 let claim:ReturnType<typeof claimHistoryResponseEvidence>|undefined;
 try{await other.capture();const scope=f.history.grantSessions(f.actor,[otherActor]),q=await f.history.query(f.actor,{query:'harbor',scope});expect(q.hits.some(h=>h.document.providerId==='other')).toBe(true);
  claim=claimHistoryResponseEvidence(f.actorAuthority,f.actor,q.evidence,{actorToken:f.actor,bootId:f.actorAuthority.bootId,providerId:'synthetic',sessionId:'session-a',snapshotId:'claimed-fixture',requestDigest:'fixture-digest',runId:'run',assistantTurnId:'assistant',assistantEntryId:'run:assistant:s-response',userTurnId:'current-turn',userRevision:1,throughSeq:2,contentDigest:'fixture-content'});
  const foreign=claim.witnesses.find(w=>w.providerId==='other')!;expect(foreign.sessionId).toBe('session-a');expect(foreign.refs).toEqual([]);expect(claim.witnesses.find(w=>w.providerId==='synthetic')!.refs.length).toBeGreaterThan(0);
 }finally{for(const w of claim?.witnesses??[])w.retire();await other.close();await f.close()}
},10000);

it('unchanged snapshot bytes on a replaced native file identity after claim cannot authorize response',async()=>{
 const f=await fixture();f.setStreamHook(async()=>{f.replaceSnapshotIdentity()});
 try{await expect(f.port.run(f.input)).rejects.toThrow();expect((await f.store.read('session-a')).entries.some(e=>e.kind==='assistant')).toBe(false);expect(()=>readHistoryEvidence(f.actorAuthority,f.actor,f.old.result.evidence)).toThrow()}finally{await f.close()}
},10000);

it.each(['assistant','success'] as const)('uncertain %s acknowledgement never renews or replays selected H continuation',async phase=>{
 const f=await fixture(),append=(fs.promises.appendFile as any).getMockImplementation(),begin=f.runtimeContext.beginHistoryResponse;let cap:object|undefined,snapshot:object|undefined,owned:any,failed=false;
 vi.spyOn(f.runtimeContext,'beginHistoryResponse').mockImplementation((token:any,value:any,input:any)=>{snapshot=value;owned=input;return cap=begin(token,value,input)});
 vi.spyOn(fs.promises,'appendFile').mockImplementation(async(...args:any[])=>{const result=await append(...args);if(!failed&&(phase==='assistant'?String(args[1]).includes('"kind":"assistant"'):String(args[1]).includes('"result":"success"'))){failed=true;throw Error('SYNTHETIC_ACK_UNKNOWN')}return result});
 try{if(phase==='assistant')await expect(f.port.run(f.input)).rejects.toThrow();else expect((await f.port.run(f.input)).status).toBe('sent');expect(failed).toBe(true);expect(f.sends).toBe(1);
  const entries=(await f.store.read('session-a')).entries;expect(entries.filter(e=>e.kind==='assistant')).toHaveLength(1);expect(entries.filter(e=>e.kind==='assistant_settlement'&&e.payload.result==='success')).toHaveLength(phase==='success'?1:0);
  await expect(f.runtimeContext.prepareHistoryResponseStep(f.actor,cap)).rejects.toThrow();expect(()=>begin(f.actor,snapshot,owned)).toThrow();expect(()=>readHistoryEvidence(f.actorAuthority,f.actor,f.old.result.evidence)).toThrow();
 }finally{await f.close()}
},10000);

it.each([['delete',1],['rewind',1],['append',1],['delete',2],['rewind',2],['append',2]] as const)('ordinary %s before response phase %s retires response but still applies user mutation and native fanout',async(kind,phase)=>{
 const f=await fixture(),prepare=f.runtimeContext.prepareHistoryResponseStep;let calls=0,applied=false;
 vi.spyOn(f.runtimeContext,'prepareHistoryResponseStep').mockImplementation(async(...args:any[])=>{await prepare(...args);if(++calls===phase){if(kind==='delete')await f.store.deleteConversation('session-a');else if(kind==='rewind')await f.store.append('session-a',{id:'rewind-ordinary',kind:'turn_rewind',payload:{anchorUserTurnId:'current-turn',disposition:'keep_user',reason:'regenerate'}});else await f.store.append('session-a',{id:'ordinary-user',kind:'user',turnId:'ordinary',revision:1,payload:{text:'new synthetic user'}});applied=true;expect(()=>readHistoryEvidence(f.actorAuthority,f.actor,f.old.result.evidence)).toThrow()}});
 try{await expect(f.port.run(f.input)).rejects.toThrow();expect(applied).toBe(true);const entries=(await f.store.read('session-a')).entries;if(kind==='delete')expect(entries).toEqual([]);else expect(entries.some(e=>e.id===(kind==='rewind'?'rewind-ordinary':'ordinary-user'))).toBe(true);expect(entries.some(e=>e.kind==='assistant_settlement'&&e.payload.result==='success')).toBe(false);expect(f.observed.some(e=>e.type==='text_message_end')).toBe(false)}finally{await f.close()}
},10000);
