import OpenAI from "openai";
import {afterEach,expect,it,vi} from "vitest";
// Real SQLite / filesystem integration cases: the 5 s default is too tight on CI runners, so this file allows 30 s. Other files keep the default.
vi.setConfig({ testTimeout: 30_000, hookTimeout: 30_000 });
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import {randomUUID,randomBytes} from "node:crypto";
import {openMemoryRepository} from "../memory-core/repository";
import {createSmhFixture} from "./smh-fixture.test-support";
import {createMainContext} from "./main-context";
import {createMainResponsesBinding,createMainOpenRouterBoundedLimits,type ResponsesSdkClient} from "./main-responses-binding";
import {createOpenRouterExpense,validateOpenRouterPreflight,openRouterUsageCost,OPENROUTER_RESERVATION_NANODOLLARS} from "./openrouter-bounded";
const metadata=()=>({data:{id:"openai/gpt-6-luna",endpoints:[{tag:"openai",model_id:"openai/gpt-6-luna",provider_name:"OpenAI",context_length:1050000,max_prompt_tokens:922000,max_completion_tokens:128000,status:0,supported_parameters:["max_tokens"],pricing:{prompt:"0.0000001",completion:"0.0000005",input_cache_read:"0.00000001",input_cache_write:"0.000000125",web_search:"0.01",discount:0,overrides:[{min_prompt_tokens:272000,prompt:"0.0000002",completion:"0.00000075",input_cache_read:"0.00000002",input_cache_write:"0.00000025"}]}}]}});
const credit=()=>({data:{limit:1,limit_reset:null,limit_remaining:1,include_byok_in_limit:true}});
const response=(cost=0.000001)=>({id:"resp_synthetic",object:"response",status:"completed",model:"openai/gpt-6-luna",provider:"OpenAI",output:[],usage:{input_tokens:12,output_tokens:2,total_tokens:14,cost,cost_details:{upstream_inference_cost:cost},server_tool_cost:0}});
const cleanup:Array<()=>void>=[];afterEach(()=>{vi.unstubAllGlobals();for(const close of cleanup.splice(0))close()});
function repository(){const root=fs.mkdtempSync(path.join(os.tmpdir(),"firefly-openrouter-ledger-")),key=randomBytes(32),file=path.join(root,"memory.sqlite");let repo=openMemoryRepository({databasePath:file,key,clock:()=>1700000000000});cleanup.push(()=>{repo.close();key.fill(0);fs.rmSync(root,{recursive:true,force:true})});return {get repo(){return repo},open:()=>{repo.close();repo=openMemoryRepository({databasePath:file,key,clock:()=>1700000000001})},expense:(bootId=randomUUID())=>createOpenRouterExpense({contextCommand:async c=>repo.contextCommand(c)},bootId)};}
it("uses a whole-provider ceiling independently of small estimated selections",()=>{expect(validateOpenRouterPreflight(metadata(),credit())).toBe(415284000);expect(OPENROUTER_RESERVATION_NANODOLLARS).toBe(415284000)});
it.each(["unlimited","reset","byok-excluded","insufficient","negative"])("refuses %s key credit before billing",kind=>{const key=credit();if(kind==="unlimited")(key.data as any).limit=null;if(kind==="reset")(key.data as any).limit_reset="daily";if(kind==="byok-excluded")key.data.include_byok_in_limit=false;if(kind==="insufficient")key.data.limit_remaining=0.4;if(kind==="negative")key.data.limit=-1;expect(()=>validateOpenRouterPreflight(metadata(),key)).toThrow("MEMORY_CONTEXT_COST_UNPROVEN")});
it.each(["price","tier","cache-write","output","model","unknown-fee","endpoint-ambiguity"])("refuses drifted %s provider metadata",kind=>{const data=metadata(),endpoint=data.data.endpoints[0];if(kind==="price")endpoint.pricing.prompt="0.000001";if(kind==="tier")endpoint.pricing.overrides[0].min_prompt_tokens=270000;if(kind==="cache-write")endpoint.pricing.overrides[0].input_cache_write="0.0000003";if(kind==="output")endpoint.max_completion_tokens=64;if(kind==="model")endpoint.model_id="other";if(kind==="unknown-fee")(endpoint.pricing as any).request="0.1";if(kind==="endpoint-ambiguity")data.data.endpoints.push({...endpoint,tag:"openai/region"});expect(()=>validateOpenRouterPreflight(data,credit())).toThrow("MEMORY_CONTEXT_COST_UNPROVEN")});
it("one profile ledger survives Worker reopen, boot, session and key changes",async()=>{const f=repository(),a=f.expense(),token=await a.reserve();await expect(f.expense().reserve()).rejects.toThrow("MEMORY_CONTEXT_COST_UNCERTAIN");f.open();await expect(f.expense().reserve()).rejects.toThrow("MEMORY_CONTEXT_COST_UNCERTAIN");await a.settle(token,400000000);const b=f.expense(),next=await b.reserve();await b.settle(next,400000000);await expect(f.expense().reserve()).rejects.toThrow("MEMORY_CONTEXT_COST_LIMIT")});
it("a private uninvoked reservation can release, settlement cannot cross capabilities",async()=>{const f=repository(),a=f.expense(),b=f.expense(),token=await a.reserve();await expect(b.release(token)).rejects.toThrow("MEMORY_CONTEXT_COST_DENIED");await a.release(token);const next=await b.reserve();await b.settle(next,1000);await expect(b.settle(next,1000)).rejects.toThrow("MEMORY_CONTEXT_COST_DENIED")});
it.each(["missing","negative","over-reserve","over-output","model","tool-cost","tool-output","route"])("does not release an uncertain %s charge",kind=>{const r=response();if(kind==="missing")delete (r.usage as any).cost;if(kind==="negative")r.usage.cost=-1;if(kind==="over-reserve")r.usage.cost=0.42;if(kind==="over-output")r.usage.output_tokens=513;if(kind==="model")r.model="other";if(kind==="tool-cost")r.usage.server_tool_cost=0.01;if(kind==="tool-output")(r.output as any).push({type:"web_search_call"});if(kind==="route")r.provider="Azure";expect(()=>openRouterUsageCost(r,512)).toThrow("MEMORY_CONTEXT_COST_UNCERTAIN")});
function fixture(stream=false,useSdk=false){
 vi.stubGlobal("fetch",()=>{throw Error("NETWORK_FORBIDDEN")});const f=createSmhFixture(fs.mkdtempSync(path.join(os.tmpdir(),"firefly-openrouter-binding-")));cleanup.push(()=>{f.close();fs.rmSync(f.root,{recursive:true,force:true})});
 let revision=1,answer:any=response(),getHook:(()=>void)|undefined,sendFailure=false;const sent:any[]=[],getCalls:any[]=[],count=vi.fn(()=>{throw Error("EXACT_COUNTER_FORBIDDEN")});
 let client:any={baseURL:"https://openrouter.ai/api/v1",maxRetries:0,logLevel:"off",fetch:()=>{throw Error("NETWORK_FORBIDDEN")},get:async(url:string,opts:any)=>{getCalls.push({url,opts});getHook?.();return url==="/key"?credit():metadata()},responses:{inputTokens:{count},create:async(body:any,opts:any)=>{sent.push({body,opts});if(sendFailure)throw Error("SYNTHETIC_SEND_TIMEOUT");return stream?{controller:new AbortController(),async *[Symbol.asyncIterator](){yield {type:"response.created",response:{...response(),status:"in_progress"}};yield {type:"response.completed",response:answer}}}:answer}}};if(useSdk)client=new OpenAI({baseURL:"https://openrouter.ai/api/v1",apiKey:"synthetic-offline-key",maxRetries:0,logLevel:"off",fetch:async(url:any,init:any)=>{expect(new Headers(init.headers).get("authorization")).toBe("Bearer synthetic-offline-key");const pathname=new URL(String(url)).pathname;if(init.method==="GET"){getCalls.push({url:pathname});getHook?.();return new Response(JSON.stringify(pathname.endsWith("/key")?credit():metadata()),{headers:{"content-type":"application/json"}})}expect(pathname).toBe("/api/v1/responses");sent.push({body:JSON.parse(init.body)});return new Response(JSON.stringify(answer),{headers:{"content-type":"application/json"}})}});
 else client.responses._client=client;client.responses.inputTokens._client=client;
 const expense=createOpenRouterExpense(f.transport,randomUUID()),binding=createMainResponsesBinding({enabled:true,client:client as ResponsesSdkClient,limits:createMainOpenRouterBoundedLimits(20000),expense,configuration:()=>({revision,config:{provider:"synthetic-custom",baseUrl:client.baseURL,model:"openai/gpt-6-luna",explicitTransport:"responses"}})})!;
 const request={model:"openai/gpt-6-luna",maxTokens:512,stream,messages:[{role:"system" as const,content:"synthetic fixed"},{role:"user" as const,content:"synthetic"}]};
 const prepare=(units:any[])=>binding.prepare({...request,messages:[request.messages[0],...units.flatMap(u=>u.messages.map((m:any)=>({role:m.role,content:m.text})))]}),context=createMainContext({registry:f.registry,transport:f.transport,actorAuthority:f.actorAuthority,counter:binding.counter,budget:binding.budget,clock:()=>1700000000000,prepare,prepareS:prepare});
 return {...f,binding,context,request,sent,getCalls,count,expense,setAnswer:(a:any)=>{answer=a},failSend:()=>{sendFailure=true},bump:()=>{revision++},onGet:(hook:()=>void)=>{getHook=hook},assemble:async()=>{const source=await f.source("synthetic");const snapshot=await context.assemble(f.actor,{sessionId:"session-a",sourceRefs:[source.ref]});return {source,snapshot,permit:await context.validateForDispatch(f.actor,snapshot)}}};
}
it("pins Luna Responses routing and output without calling an exact counter",async()=>{const f=fixture(),prepared=f.binding.prepare(f.request);expect(prepared.body).toMatchObject({model:"openai/gpt-6-luna",max_output_tokens:512,store:false,truncation:"disabled",provider:{only:["openai"],order:["openai"],allow_fallbacks:false,require_parameters:true}});expect(f.binding.counter.capability.mode).toBe("estimate");expect(await f.binding.counter.count(prepared)).toBe(Buffer.byteLength(JSON.stringify(prepared.body))+1024);expect(f.count).not.toHaveBeenCalled();const {snapshot,permit}=await f.assemble();expect(snapshot.promptTokens).toBeUndefined();expect((await f.binding.dispatch(f.context,f.actor,permit)).status).toBe("sent");expect(f.sent).toHaveLength(1);expect(f.sent[0].body).toEqual(snapshot.request.body);expect(f.sent[0].opts.maxRetries).toBe(0);await expect(f.binding.dispatch(f.context,f.actor,permit)).rejects.toThrow("MEMORY_CONTEXT_PERMIT_USED");expect(f.sent).toHaveLength(1);});
it("metadata-time config drift releases an uninvoked reservation",async()=>{const f=fixture(),{permit}=await f.assemble();f.onGet(f.bump);await expect(f.binding.dispatch(f.context,f.actor,permit)).rejects.toThrow("MEMORY_CONTEXT_REQUEST_CHANGED");expect(f.sent).toHaveLength(0);const next=await f.expense.reserve();await f.expense.release(next)});
it("source edit during preflight denies dispatch and releases only the uninvoked reservation",async()=>{const f=fixture(),{source,permit}=await f.assemble();f.onGet(()=>{f.write(source.id,{text:"changed",role:"user",trust:"direct-user-event"})});await expect(f.binding.dispatch(f.context,f.actor,permit)).rejects.toThrow();expect(f.sent).toHaveLength(0);const next=await f.expense.reserve();await f.expense.release(next)});
it("missing post-use cost retains reservation and prevents another send",async()=>{const f=fixture(),{permit}=await f.assemble(),r=response();delete (r.usage as any).cost;f.setAnswer(r);expect((await f.binding.dispatch(f.context,f.actor,permit)).status).toBe("result-unknown");const next=await f.assemble();await expect(f.binding.dispatch(f.context,f.actor,next.permit)).rejects.toThrow("MEMORY_CONTEXT_COST_UNCERTAIN");expect(f.sent).toHaveLength(1)});
it("a streamed completion settles before it reaches the canonical consumer",async()=>{const f=fixture(true),{permit}=await f.assemble(),sent=await f.binding.dispatch(f.context,f.actor,permit);expect(sent.status).toBe("sent");if(sent.status!=="sent")return;for await(const event of sent.result as any){if(event.type==="response.completed"){const next=await f.expense.reserve();await f.expense.release(next)}}});
it("an abandoned stream retains the charge and never retries",async()=>{const f=fixture(true),{permit}=await f.assemble(),sent=await f.binding.dispatch(f.context,f.actor,permit);if(sent.status!=="sent")throw Error("NO_STREAM");for await(const event of sent.result as any){expect(event.type).toBe("response.created");break}await expect(f.expense.reserve()).rejects.toThrow("MEMORY_CONTEXT_COST_UNCERTAIN");expect(f.sent).toHaveLength(1)});

it("the installed SDK uses synthetic bearer-authenticated metadata and one pinned generation",async()=>{const f=fixture(false,true),{permit}=await f.assemble();expect((await f.binding.dispatch(f.context,f.actor,permit)).status).toBe("sent");expect(f.getCalls.map(c=>c.url)).toEqual(["/api/v1/key","/api/v1/models/openai/gpt-6-luna/endpoints"]);expect(f.sent).toHaveLength(1);expect(f.sent[0].body.provider.allow_fallbacks).toBe(false);const next=await f.expense.reserve();await f.expense.release(next)});
it("preflight timeout sends nothing and releases only its uninvoked reservation",async()=>{const f=fixture(),{permit}=await f.assemble();f.onGet(()=>{throw Error("SYNTHETIC_METADATA_TIMEOUT")});await expect(f.binding.dispatch(f.context,f.actor,permit)).rejects.toThrow("SYNTHETIC_METADATA_TIMEOUT");expect(f.sent).toHaveLength(0);const next=await f.expense.reserve();await f.expense.release(next)});
it("invoked SDK timeout retains the full charge reservation without retry",async()=>{const f=fixture(),{permit}=await f.assemble();f.failSend();expect((await f.binding.dispatch(f.context,f.actor,permit)).status).toBe("result-unknown");await expect(f.expense.reserve()).rejects.toThrow("MEMORY_CONTEXT_COST_UNCERTAIN");expect(f.sent).toHaveLength(1)});
it("sender revocation at the final callback makes no paid send",async()=>{const f=fixture(),{permit}=await f.assemble();expect((await f.binding.dispatch(f.context,f.actor,permit,undefined,()=>{throw Error("MEMORY_CONTEXT_RUN_STALE")})).status).toBe("result-unknown");expect(f.sent).toHaveLength(0);const next=await f.expense.reserve();await f.expense.release(next)});
it("cancelled metadata preflight releases the uninvoked reservation",async()=>{const f=fixture(),{permit}=await f.assemble(),abort=new AbortController();f.onGet(()=>abort.abort());await expect(f.binding.dispatch(f.context,f.actor,permit,abort.signal)).rejects.toThrow("MEMORY_CONTEXT_CANCELLED");expect(f.sent).toHaveLength(0);const next=await f.expense.reserve();await f.expense.release(next)});
