import { beforeEach, expect, it, vi } from "vitest";
import { createDefaultProactiveState } from "./proactive-policy";
const mocks = vi.hoisted(() => ({ state: {} as any, send: vi.fn(), history: vi.fn(), log: vi.fn() }));
vi.mock("electron", () => ({ powerMonitor: { on: vi.fn(), getSystemIdleTime: () => 0 } }));
vi.mock("../chats/chats-store", () => ({ listSessions: () => [], getSessionByPurpose: () => null }));
vi.mock("../chats/chats-ipc", () => ({ broadcastChatsChanged: vi.fn() }));
vi.mock("../channels/init", () => ({ setChannelsConversationLifecycle: vi.fn() }));
vi.mock("../channels/manager", () => ({ channelManager: { getAdapter: () => ({ getStatus: () => ({ phase: "running" }), send: mocks.send }) } }));
vi.mock("../channels/history-log", () => ({ appendHistory: mocks.history }));
vi.mock("../channels/message-log", () => ({ appendLog: mocks.log }));
vi.mock("../orchestrator", () => ({ buildAlwaysOnContext: async () => "", buildMemoryInjection: async () => "", buildWorldbookContext: async () => "" }));
vi.mock("../rag", () => ({ searchMemory: async () => [] }));
vi.mock("../prompts/prompt-loader", () => ({ loadPromptFile: () => "persona" }));
vi.mock("../settings/model-settings", () => ({ loadModelSettings: () => ({ provider: "fixture", apiKey: "synthetic" }), getDefaultModelProfile: () => ({ id: "fixture" }), resolveModelSettingsProfile: (settings: unknown) => settings }));
vi.mock("../settings-store", () => ({ loadUserProfile: () => ({ timezone: "UTC" }) }));
vi.mock("./proactive-state-store", () => ({ loadProactiveState: () => mocks.state, saveProactiveState: vi.fn() }));
vi.mock("./proactive-model", () => ({ runProactiveModel: async () => ({ kind: "send", text: "第一句。第二句。" }) }));
import { createProactiveLifecycle } from "./proactive-lifecycle";
import { rememberProactiveChannelRecipient } from "../channels/proactive-delivery";
beforeEach(() => { vi.clearAllMocks(); mocks.state = createDefaultProactiveState(); });
it.each(["close", "invalidate"] as const)("%s during an actual first segment drains that send and blocks the second segment and late commit", async action => {
  let entered!: () => void, release!: () => void;
  const started = new Promise<void>(resolve => { entered = resolve; }), held = new Promise<void>(resolve => { release = resolve; });
  mocks.send.mockImplementationOnce(async () => { entered(); await held; return { ok: true }; }).mockResolvedValue({ ok: true });
  rememberProactiveChannelRecipient({ channel: "wechat", chatId: "fixture-chat", senderId: "fixture-user", text: "hi", at: new Date() }, "fixture-session");
  const lifecycle = createProactiveLifecycle({ loadGeneralSettings: () => ({ proactiveChatMode: "on", proactiveDeliveryTarget: "wechat", mobileMessageSegmentation: "on" } as any) });
  lifecycle.initializeProactiveChatService();
  const logs = vi.spyOn(console, "log");
  const running = lifecycle.getProactiveChatService()!.evaluateCandidate({ sceneId: "work_break", score: 90, sceneCooldownMs: 0 });
  await started;
  if (action === "invalidate") lifecycle.getProactiveChatService()!.invalidate();
  let closed = false;
  const closing = (action === "close" ? lifecycle.close() : running).then(() => { closed = true; });
  await Promise.resolve(); expect(closed).toBe(false); expect(mocks.send).toHaveBeenCalledTimes(1);
  release(); await running; await closing; await lifecycle.close();
  expect(mocks.send.mock.calls.map(([message]) => message.parts[0].text)).toEqual(["第一句。"]);
  expect(mocks.history).toHaveBeenCalledWith("fixture-session", "assistant", "第一句。");
  expect(mocks.state.unansweredCount).toBe(0);
  expect(mocks.state.lastProactiveAt).toEqual(expect.any(Number));
  expect(mocks.state.lastFiredAt.work_break).toBe(mocks.state.lastProactiveAt);
  expect(logs.mock.calls.some(([event]) => event === "[Proactive] message_committed")).toBe(false);
  logs.mockRestore();
});
