import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {spawn} from 'node:child_process';import {createPackageWithOptions} from '@electron/asar';import {createHash} from 'node:crypto';
const cwd=process.cwd();assert.equal(path.parse(cwd).root.slice(0,2).toUpperCase(),'E:');
const output=path.join(cwd,'output/openrouter-usd1/diagnostics/native-'+Date.now()),source=path.join(output,'app-source');fs.mkdirSync(source,{recursive:true});
fs.cpSync(path.join(cwd,'dist/main'),path.join(source,'compiled'),{recursive:true});fs.cpSync(path.join(cwd,'dist/preload'),path.join(source,'dist/preload'),{recursive:true});
fs.copyFileSync('scripts/verify/memory-openrouter-once/entry.cjs',path.join(source,'entry.cjs'));fs.mkdirSync(path.join(source,'assets'),{recursive:true});fs.copyFileSync('assets/tray-icon.ico',path.join(source,'assets/tray-icon.ico'));
fs.writeFileSync(path.join(source,'package.json'),JSON.stringify({name:'firefly-openrouter-synthetic',version:'0.0.0',main:'entry.cjs'}));
const packaged=path.join(output,'win-unpacked');fs.cpSync(path.join(cwd,'node_modules/electron/dist'),packaged,{recursive:true});fs.renameSync(path.join(packaged,'electron.exe'),path.join(packaged,'FireflyOpenRouterSynthetic.exe'));await createPackageWithOptions(source,path.join(packaged,'resources/app.asar'),{});
const admissionRoots=['E:/Codex/2026-10-01/task/memory-online-once-admission-55df896','E:/Codex/2026-10-01/task/memory-openrouter-usd1-admission-20261002'];const snapshot=()=>admissionRoots.map(root=>['arm.json','boot.json','spent.json','ledger.json'].map(name=>{const p=path.join(root,name);return fs.existsSync(p)?createHash('sha256').update(fs.readFileSync(p)).digest('hex'):null;}));const initial=snapshot(),runs=[];
const pause=ms=>new Promise(r=>setTimeout(r,ms));async function until(check){for(let i=0;i<600;i++){if(check())return;await pause(20);}throw Error('DRIVER_TIMEOUT');}
for(const isPackaged of (process.env.FIREFLY_OPENROUTER_VERIFY_CASE?[false]:[false,true]))for(const mode of (process.env.FIREFLY_OPENROUTER_VERIFY_CASE?[process.env.FIREFLY_OPENROUTER_VERIFY_CASE]:['startup','prepare','form-close','success','cancel','decline','expired','uncertain','duplicate','bad-input','sender','network','late-arm','transport-runtime','http-failure','json-failure','identity-failure','usage-failure','cost-failure','network-failure','partial-cost','zero-cost'])){
 const root=path.join(output,(isPackaged?'asar-':'dev-')+mode),sourceRoot=root+'-source';for(const sub of ['temp','cache','logs','initial-userdata','fake-admission'])fs.mkdirSync(path.join(root,sub),{recursive:true});fs.mkdirSync(sourceRoot,{recursive:true});
 const now=Date.now();fs.writeFileSync(path.join(root,mode==='late-arm'?'late-arm-fixture.json':'fake-admission/arm.json'),JSON.stringify({armed:true,experimentId:'memory-h-openrouter-usd1-20261002',priorAttempts:0,budgetNanoUsd:1e9,inputNanoUsdPerToken:300,outputNanoUsdPerToken:1200,currency:'USD',model:'deepseek/deepseek-v4.1-flash',endpoint:'https://openrouter.ai/api/v1/chat/completions',provider:'deepseek',maxAttempts:2,bodySha256:'b3d2ca0321c5685149f96f9dae5f2e084a66be6f54c9ae05f3a08e9972351087',priceVerifiedAt:now-1000,expiresAt:mode==='expired'?now-1:now+3600000}));
 const env={...process.env,ELECTRON_RUN_AS_NODE:undefined,TEMP:path.join(root,'temp'),TMP:path.join(root,'temp'),TMPDIR:path.join(root,'temp'),APPDATA:sourceRoot,LOCALAPPDATA:sourceRoot,ELECTRON_LOG_FILE:path.join(root,'logs/electron.log'),CHROME_LOG_FILE:path.join(root,'logs/chromium.log'),FIREFLY_OPENROUTER_DIAGNOSTIC_ROOT:root,FIREFLY_OPENROUTER_CASE:mode};
 const exe=isPackaged?path.join(packaged,'FireflyOpenRouterSynthetic.exe'):path.join(cwd,'node_modules/electron/dist/electron.exe'),args=[...(isPackaged?[]:[source]),'--firefly-memory-openrouter-once','--user-data-dir='+path.join(root,'initial-userdata'),'--disk-cache-dir='+path.join(root,'cache'),'--crash-dumps-dir='+path.join(root,'logs/crashes')];
 function launch(caseName=mode){const child=spawn(exe,args,{cwd,env:{...env,FIREFLY_OPENROUTER_CASE:caseName},windowsHide:false,stdio:['ignore','pipe','pipe']});let stderr='',stdout='';child.stdout.on('data',b=>stdout+=b.toString());child.stderr.on('data',b=>stderr+=b.toString());const timer=setTimeout(()=>child.kill(),30000);return {child,done:new Promise((resolve,reject)=>{child.on('error',reject);child.on('close',code=>{clearTimeout(timer);fs.writeFileSync(path.join(root,'logs/process-'+child.pid+'.json'),JSON.stringify({stdout,stderr}));resolve(code);});})};}
 const primary=launch();if(mode==='duplicate'){await until(()=>fs.existsSync(path.join(root,'readiness.json'))&&JSON.parse(fs.readFileSync(path.join(root,'readiness.json'),'utf8')).menuReady);const secondary=launch();assert.equal(await secondary.done,0);assert.ok(fs.existsSync(path.join(root,'secondary-'+secondary.child.pid+'.json')));fs.writeFileSync(path.join(root,'quit-verification'),'');}
 assert.equal(await primary.done,0,'native failure '+root);runs.push(JSON.parse(fs.readFileSync(path.join(root,'result-'+mode+'.json'),'utf8')));assert.deepEqual(snapshot(),initial);
 if(['success','decline','startup'].includes(mode)){const restart=launch('restart');assert.equal(await restart.done,0,'restart failure '+root);runs.push(JSON.parse(fs.readFileSync(path.join(root,'result-restart.json'),'utf8')));assert.deepEqual(snapshot(),initial);}
}
fs.writeFileSync('output/openrouter-usd1/diagnostics/native-results.json',JSON.stringify({output,totalScenarios:runs.length,runs,actualAdmissionUnchanged:true,externalModelRequests:0,localHttpRequests:runs.reduce((sum,r)=>sum+r.localRequests,0),realConfigurationReads:0},null,2));console.log(JSON.stringify({output,totalScenarios:runs.length,actualAdmissionUnchanged:true}));
