import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {createRequire} from 'node:module';
import {DatabaseSync} from 'node:sqlite';
import {afterEach,it,expect} from 'vitest';
import {openMemoryRepository} from '../memory-core/repository';
const roots:string[]=[];afterEach(()=>{for(const r of roots.splice(0))fs.rmSync(r,{recursive:true,force:true})});
const source=path.join(__dirname,'fixtures/v8-writer'),hash=(file:string)=>createHash('sha256').update(fs.readFileSync(file)).digest('hex');
function fixture(){const root=fs.mkdtempSync(path.join(os.tmpdir(),'history-v8-'));roots.push(root);const file=path.join(root,'memory.sqlite'),manifest=JSON.parse(fs.readFileSync(path.join(source,'manifest.json'),'utf8'));for(const name of ['memory.sqlite','memory.sqlite.auth','v8-writer.cjs'])expect(hash(path.join(source,name))).toBe(manifest.hashes[name]);for(const suffix of ['','.auth'])fs.copyFileSync(path.join(source,'memory.sqlite'+suffix),file+suffix);return {root,file,key:Buffer.alloc(32,8)}}
const bytes=(root:string)=>fs.readdirSync(root).sort().map(name=>({name,bytes:fs.readFileSync(path.join(root,name))}));
it('actual retained v8 writer fixture upgrades additively to v9 without rewriting ciphertext',()=>{const f=fixture(),before=new DatabaseSync(f.file),payload=before.prepare("SELECT payload FROM sources WHERE id='actual-v8-source'").get()?.payload;expect(before.prepare('PRAGMA user_version').get()?.user_version).toBe(8);before.close();const repo=openMemoryRepository({databasePath:f.file,key:f.key});expect(repo.readRows('sources','scope-a')[0].payload).toEqual({text:'ACTUAL_V8_SYNTHETIC_RECORD'});repo.close();const db=new DatabaseSync(f.file);try{expect(db.prepare('PRAGMA user_version').get()?.user_version).toBe(9);expect(db.prepare("SELECT payload FROM sources WHERE id='actual-v8-source'").get()?.payload).toEqual(payload);expect(db.prepare("SELECT name FROM sqlite_master WHERE name='history_records'").get()?.name).toBe('history_records')}finally{db.close()}});
it('failed additive v9 migration preserves all actual v8 bytes',()=>{const f=fixture(),db=new DatabaseSync(f.file);db.exec('CREATE INDEX history_records_by_partition ON sources(scope_key)');db.close();const snapshot=bytes(f.root);expect(()=>openMemoryRepository({databasePath:f.file,key:f.key})).toThrow();expect(bytes(f.root)).toEqual(snapshot)});
it.each(['wrong-key','future'])('%s refuses before altering database/auth files',kind=>{const f=fixture();if(kind==='future'){const db=new DatabaseSync(f.file);db.exec('PRAGMA user_version=99');db.close()}const snapshot=bytes(f.root);expect(()=>openMemoryRepository({databasePath:f.file,key:kind==='wrong-key'?Buffer.alloc(32,9):f.key})).toThrow();expect(bytes(f.root)).toEqual(snapshot)});
it('actual old v8 refuses v9 and complete DB/auth backup restores into a separate owned root',()=>{const f=fixture(),backup=bytes(f.root),repo=openMemoryRepository({databasePath:f.file,key:f.key});repo.close();const old=createRequire(import.meta.url)(path.join(source,'v8-writer.cjs')),upgraded=bytes(f.root);expect(()=>old.openMemoryRepository({databasePath:f.file,key:f.key})).toThrow('MEMORY_SCHEMA_UNSUPPORTED');expect(bytes(f.root)).toEqual(upgraded);const restored=path.join(f.root,'restored');fs.mkdirSync(restored);for(const b of backup)fs.writeFileSync(path.join(restored,b.name),b.bytes);const actual=old.openMemoryRepository({databasePath:path.join(restored,'memory.sqlite'),key:f.key});expect(actual.readRows('sources','scope-a')[0].payload).toEqual({text:'ACTUAL_V8_SYNTHETIC_RECORD'});actual.close()});
