export const FIREFLY_STICKERS = [
  {"id": "firefly-hug", "file": "hug.png", "sourceFile": "抱抱.png", "description": "张开双臂，抱抱", "phrases": ["张开双臂，抱抱", "想给你一个拥抱"]},
  {"id": "firefly-meal", "file": "meal.png", "sourceFile": "吃饭.png", "description": "端着饭碗，吃饭", "phrases": ["端着饭碗，吃饭", "到吃饭时间啦"]},
  {"id": "firefly-cry", "file": "cry.png", "sourceFile": "大哭.png", "description": "流着眼泪，大哭", "phrases": ["流着眼泪，大哭", "难过得哭了"]},
  {"id": "firefly-thumbs-up", "file": "thumbs-up.png", "sourceFile": "点赞.png", "description": "竖起拇指，点赞", "phrases": ["竖起拇指，点赞", "做得真好"]},
  {"id": "firefly-holiday", "file": "holiday.png", "sourceFile": "放假.png", "description": "躺着休息，放假", "phrases": ["躺着休息，放假", "放假好好休息吧"]},
  {"id": "firefly-shy", "file": "shy.png", "sourceFile": "害羞.png", "description": "捂着嘴，害羞", "phrases": ["捂着嘴，害羞", "有一点不好意思"]},
  {"id": "firefly-tea", "file": "tea.png", "sourceFile": "喝茶.png", "description": "捧着茶杯，喝茶", "phrases": ["捧着茶杯，喝茶", "一起歇一会儿吧"]},
  {"id": "firefly-cheer", "file": "cheer.png", "sourceFile": "加油.png", "description": "握拳鼓励，加油", "phrases": ["握拳鼓励，加油", "我为你加油"]},
  {"id": "firefly-happy", "file": "happy.png", "sourceFile": "开心.png", "description": "双手捧脸，开心", "phrases": ["双手捧脸，开心", "现在心情很好"]},
  {"id": "firefly-sleepy", "file": "sleepy.png", "sourceFile": "困了.png", "description": "揉眼睛，困了", "phrases": ["揉眼睛，困了", "有点想睡觉了"]},
  {"id": "firefly-tired", "file": "tired.png", "sourceFile": "累了.png", "description": "趴着休息，累了", "phrases": ["趴着休息，累了", "先休息一下吧"]},
  {"id": "firefly-hello", "file": "hello.png", "sourceFile": "你好.png", "description": "张开手打招呼，你好", "phrases": ["张开手打招呼，你好", "你好呀"]},
  {"id": "firefly-kiss", "file": "kiss.png", "sourceFile": "亲亲.png", "description": "闭眼送吻，亲亲", "phrases": ["闭眼送吻，亲亲", "送你一个亲亲"]},
  {"id": "firefly-angry", "file": "angry.png", "sourceFile": "生气.png", "description": "鼓起脸，生气", "phrases": ["鼓起脸，生气", "有点生气了"]},
  {"id": "firefly-received", "file": "received.png", "sourceFile": "收到.png", "description": "抬手回应，收到", "phrases": ["抬手回应，收到", "明白啦"]},
  {"id": "firefly-good-night", "file": "good-night.png", "sourceFile": "晚安.png", "description": "抱着枕头，晚安", "phrases": ["抱着枕头，晚安", "愿你睡个好觉"]},
  {"id": "firefly-upset", "file": "upset.png", "sourceFile": "委屈.png", "description": "眼含泪水，委屈", "phrases": ["眼含泪水，委屈", "觉得有点委屈"]},
  {"id": "firefly-miss-me", "file": "miss-me.png", "sourceFile": "想我没.png", "description": "指着脸询问，想我没", "phrases": ["指着脸询问，想我没", "有没有想我呀"]},
  {"id": "firefly-thanks", "file": "thanks.png", "sourceFile": "谢谢.png", "description": "抱着花束，谢谢", "phrases": ["抱着花束，谢谢", "谢谢你呀"]},
  {"id": "firefly-good-morning", "file": "good-morning.png", "sourceFile": "早安.png", "description": "挥手问候，早安", "phrases": ["挥手问候，早安", "早上好"]},
  {"id": "firefly-okay", "file": "okay.png", "sourceFile": "OK.png", "description": "做出OK手势", "phrases": ["做出OK手势", "好呀，没问题"]},
] as const;
