import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import {randomBytes} from "node:crypto";
import {DatabaseSync} from "node:sqlite";
import {afterEach,it,expect} from "vitest";
import {openMemoryRepository} from "./repository";
const roots:string[]=[],repositories:ReturnType<typeof openMemoryRepository>[]=[];
afterEach(()=>{for(const r of repositories.splice(0))r.close();for(const p of roots.splice(0))fs.rmSync(p,{recursive:true,force:true})});
const identity={providerId:"synthetic",sessionId:"session-a",messageId:"message-a"};
const observation={...identity,contentRevision:1,generation:"generation-a",state:"live",role:"user",trust:"direct-user-event",fingerprint:"a".repeat(64)};
function fixture(){const root=fs.mkdtempSync(path.join(os.tmpdir(),"source-ledger-"));roots.push(root);const databasePath=path.join(root,"memory.sqlite"),key=randomBytes(32);const repo=openMemoryRepository({databasePath,key});repositories.push(repo);let n=0;const command=(kind:string,body:unknown,scopeKey="scope-a")=>(repo as any).sourceCommand({kind,scopeKey,commandId:"source-command-"+ ++n,body});return{root,databasePath,key,repo,command};}
function publish(f:ReturnType<typeof fixture>,value=observation){const reservation=f.command("reserve",{identity,expectedRef:null});return f.command("finish",{sourceId:reservation.sourceId,operationId:reservation.operationId,observation:value});}
it("publishes a bound source and preserves its reference on duplicate observation",()=>{const f=fixture(),first=publish(f),second=publish(f);expect(second).toEqual(first);expect(first.binding).toEqual({...identity,contentRevision:1,generation:"generation-a"});expect(f.command("validate",{sourceRef:first})).toMatchObject({role:"user",trust:"direct-user-event"});});
it("leaves pending durable across close/reopen until its owning operation reconciles",()=>{const f=fixture(),ref=publish(f),reservation=f.command("reserve",{identity,expectedRef:ref});expect(()=>f.command("validate",{sourceRef:ref})).toThrow("MEMORY_SOURCE_PENDING");f.repo.close();const reopened=openMemoryRepository({databasePath:f.databasePath,key:f.key});repositories.push(reopened);const pending=(reopened as any).sourceCommand({kind:"pending",scopeKey:"scope-a",body:{identity}});expect(pending.operationId).toBe(reservation.operationId);expect(()=>(reopened as any).sourceCommand({kind:"validate",scopeKey:"scope-a",body:{sourceRef:ref}})).toThrow("MEMORY_SOURCE_PENDING");});
it.each(["role","trust","fingerprint"])("rejects changed %s at the same provider revision",field=>{const f=fixture(),ref=publish(f),reservation=f.command("reserve",{identity,expectedRef:ref});const value={...observation,[field]:field==="role"?"assistant":field==="trust"?"history":"b".repeat(64)};expect(()=>f.command("finish",{sourceId:reservation.sourceId,operationId:reservation.operationId,observation:value})).toThrow("MEMORY_SOURCE_VERSION_MISMATCH");expect(()=>f.command("validate",{sourceRef:ref})).toThrow("MEMORY_SOURCE_PENDING");});
it("changes trust and role only under a new bound revision and blocks old evidence",()=>{const f=fixture(),old=publish(f),fresh=publish(f,{...observation,contentRevision:2,role:"assistant",trust:"model",fingerprint:"b".repeat(64)});expect(fresh.revision).toBeGreaterThan(old.revision);expect(()=>f.command("validate",{sourceRef:old})).toThrow("MEMORY_SOURCE_STALE");expect(()=>f.repo.execute({kind:"appendEvidence",scopeKey:"scope-a",commandId:"stale-evidence",body:{evidenceId:"stale",sourceRef:old,text:"quoted"}})).toThrow("MEMORY_SOURCE_STALE");});
it("retains a tombstone and requires a new generation when the same ID is recreated",()=>{const f=fixture(),old=publish(f);publish(f,{...observation,state:"deleted",contentRevision:2});expect(()=>f.command("validate",{sourceRef:old})).toThrow("MEMORY_SOURCE_DELETED");expect(()=>publish(f,{...observation,contentRevision:3})).toThrow("MEMORY_SOURCE_GENERATION_REUSED");const pending=f.command("pending",{identity});const fresh=f.command("finish",{sourceId:pending.sourceId,operationId:pending.operationId,observation:{...observation,generation:"generation-b"}});expect(fresh.sourceId).toBe(old.sourceId);expect(fresh.binding.generation).not.toBe(old.binding.generation);expect(()=>f.command("validate",{sourceRef:old})).toThrow("MEMORY_SOURCE_STALE");});
it("rejects fake binding, scope, operation and legacy managed-source overwrite",()=>{const f=fixture(),ref=publish(f);expect(()=>f.command("validate",{sourceRef:{...ref,binding:{...ref.binding,messageId:"other"}}})).toThrow("MEMORY_SOURCE_STALE");expect(()=>f.command("validate",{sourceRef:ref},"scope-b")).toThrow("MEMORY_SOURCE_INVALID");expect(()=>f.command("validate",{sourceRef:{sourceId:ref.sourceId,revision:ref.revision}})).toThrow("MEMORY_SOURCE_BINDING_REQUIRED");expect(()=>f.repo.execute({kind:"registerSource",scopeKey:"scope-a",commandId:"bypass",body:{sourceRef:ref,kind:"user"}})).toThrow("MEMORY_SOURCE_MANAGED");const pending=f.command("reserve",{identity,expectedRef:ref});expect(()=>f.command("finish",{sourceId:ref.sourceId,operationId:"fake",observation})).toThrow("MEMORY_SOURCE_OPERATION_CONFLICT");expect(pending.operationId).not.toBe("fake");});
it("blocks an already claimed job while pending and after content replacement",()=>{const f=fixture(),ref=publish(f);f.repo.jobCommand({kind:"enqueue",scopeKey:"scope-a",commandId:"enqueue",body:{jobId:"job",sourceRef:ref}});const lease=f.repo.jobCommand({kind:"claim",scopeKey:"scope-a",commandId:"claim",body:{jobId:"job",leaseMs:60000}}) as any;const pending=f.command("reserve",{identity,expectedRef:ref});const body={jobId:"job",leaseToken:lease.leaseToken,proposals:[{candidateId:"candidate",evidenceId:"evidence",text:"中文 English 🌱",fact:{subjectKey:"topic",assertion:"old",assertionKind:"user-statement",time:{validFrom:null,validTo:null,referenceTime:null}}}]};expect(()=>f.repo.jobCommand({kind:"commit",scopeKey:"scope-a",commandId:"commit-old",body})).toThrow("MEMORY_SOURCE_PENDING");f.command("finish",{sourceId:ref.sourceId,operationId:pending.operationId,observation:{...observation,contentRevision:2,fingerprint:"b".repeat(64)}});expect(()=>f.repo.jobCommand({kind:"commit",scopeKey:"scope-a",commandId:"commit-stale",body})).toThrow("MEMORY_SOURCE_STALE");expect(f.repo.readRows("evidence","scope-a")).toEqual([]);});
it("migrates a v3 database, rolls a failed migration back, and refuses future schemas",()=>{const f=fixture();f.repo.close();let db=new DatabaseSync(f.databasePath);db.exec("DROP TABLE source_generations; DROP TABLE source_heads; PRAGMA user_version=3");db.close();let reopened=openMemoryRepository({databasePath:f.databasePath,key:f.key});reopened.close();db=new DatabaseSync(f.databasePath);expect(db.prepare("PRAGMA user_version").get()?.user_version).toBe(4);db.exec("PRAGMA user_version=3");db.close();expect(()=>openMemoryRepository({databasePath:f.databasePath,key:f.key})).toThrow();db=new DatabaseSync(f.databasePath);expect(db.prepare("PRAGMA user_version").get()?.user_version).toBe(3);db.exec("PRAGMA user_version=999");db.close();expect(()=>openMemoryRepository({databasePath:f.databasePath,key:f.key})).toThrow("MEMORY_SCHEMA_UNSUPPORTED");});
it("keeps locator/content fingerprints encrypted and wrong-key opening leaves files unchanged",()=>{const f=fixture();publish(f);f.repo.close();const snapshot=()=>fs.readdirSync(f.root).sort().map(name=>({name,bytes:fs.readFileSync(path.join(f.root,name)),mtime:fs.statSync(path.join(f.root,name)).mtimeMs}));const before=snapshot();const bytes=Buffer.concat(before.map(x=>x.bytes));for(const canary of [identity.providerId,identity.sessionId,identity.messageId,observation.fingerprint])expect(bytes.includes(Buffer.from(canary))).toBe(false);expect(()=>openMemoryRepository({databasePath:f.databasePath,key:randomBytes(32)})).toThrow();expect(snapshot()).toEqual(before);});
it("never reuses a retired generation after another incarnation, including restart",()=>{const f=fixture();publish(f);publish(f,{...observation,generation:"generation-b"});f.repo.close();const repo=openMemoryRepository({databasePath:f.databasePath,key:f.key});repositories.push(repo);const pending=repo.sourceCommand({kind:"reserve",scopeKey:"scope-a",commandId:"reserve-reused",body:{identity,expectedRef:null}}) as any;expect(()=>repo.sourceCommand({kind:"finish",scopeKey:"scope-a",commandId:"finish-reused",body:{sourceId:pending.sourceId,operationId:pending.operationId,observation}})).toThrow("MEMORY_SOURCE_GENERATION_REUSED");});
it("rolls source head, row, generation and command receipt back together on commit failure",()=>{const f=fixture(),ref=publish(f);f.repo.close();let fail=false;const repo=openMemoryRepository({databasePath:f.databasePath,key:f.key,fault:stage=>{if(fail&&stage==="before-receipt")throw new Error("SYNTHETIC_COMMIT_FAILED")}});repositories.push(repo);const pending=repo.sourceCommand({kind:"reserve",scopeKey:"scope-a",commandId:"fault-reserve",body:{identity,expectedRef:ref}}) as any;const command={kind:"finish",scopeKey:"scope-a",commandId:"fault-finish",body:{sourceId:pending.sourceId,operationId:pending.operationId,observation:{...observation,generation:"generation-b"}}};fail=true;expect(()=>repo.sourceCommand(command)).toThrow("SYNTHETIC_COMMIT_FAILED");expect(repo.sourceCommand({kind:"pending",scopeKey:"scope-a",body:{identity}})).toEqual(pending);const db=new DatabaseSync(f.databasePath,{readOnly:true});try{expect(db.prepare("SELECT count(*) n FROM source_generations").get()?.n).toBe(1);expect(db.prepare("SELECT count(*) n FROM command_receipts WHERE command_id='fault-finish'").get()?.n).toBe(0)}finally{db.close()}fail=false;const fresh=repo.sourceCommand(command);expect(repo.sourceCommand(command)).toEqual(fresh);expect(repo.sourceCommand({kind:"validate",scopeKey:"scope-a",body:{sourceRef:fresh}})).toMatchObject({generation:"generation-b"});});
it("does not revoke an already confirmed M projection or revision history when its source is deleted",()=>{const f=fixture(),ref=publish(f);let n=0;const execute=(kind:string,body:unknown)=>f.repo.execute({kind,scopeKey:"scope-a",commandId:"confirmed-"+kind+ ++n,body});execute("appendEvidence",{evidenceId:"evidence",sourceRef:ref,text:"synthetic prior confirmation"});execute("proposeCandidate",{candidateId:"candidate",evidenceId:"evidence",fact:{subjectKey:"topic",assertion:"confirmed",assertionKind:"user-statement",time:{validFrom:null,validTo:null,referenceTime:null}}});const active=execute("activateCandidate",{candidateId:"candidate",authorization:{reason:"policyAccepted",sourceRef:ref,policyVersion:"synthetic-prior-policy"}});const current=f.repo.current("scope-a"),history=f.repo.history("scope-a",active.id);publish(f,{...observation,state:"deleted",contentRevision:2});expect(f.repo.current("scope-a")).toEqual(current);expect(f.repo.history("scope-a",active.id)).toEqual(history);expect(()=>execute("appendEvidence",{evidenceId:"late-evidence",sourceRef:ref,text:"late"})).toThrow("MEMORY_SOURCE_DELETED");});
