import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {createHash,randomUUID} from 'node:crypto';
import {Worker} from 'node:worker_threads';
import {DatabaseSync} from 'node:sqlite';
import {app} from 'electron';
import {canonicalPath,within,resolveRuntimeProfile,applyElectronPaths} from '../../../src/main/runtime-profile';
import {createStorageContext} from '../../../src/main/storage-context';
import {createWindowsKeyProtection} from '../../../src/main/memory-core/windows-dpapi';
import {MemoryClient} from '../../../src/main/memory-core/worker-client';
import {createMainActorAuthority} from '../../../src/main/memory-core/main-actor-authority';
import {createMainSourceRegistry} from '../../../src/main/memory-sources/source-registry';
import {createMainPolicy} from '../../../src/main/memory-policy/main-policy';
import {createMainHistory,createMainHistoryProvider} from '../../../src/main/memory-history/main-history';
import {createHistoryMigration} from '../../../src/main/memory-history/history-migration';
import {createMainContext} from '../../../src/main/memory-context/main-context';
import {SyntheticSourceProvider} from '../memory-sources/synthetic-provider';
const arg=(name:string)=>process.argv.find(v=>v.startsWith(name+'='))?.slice(name.length+1),cwd=process.cwd(),root=arg('--history-probe-root'),mode=arg('--history-probe-mode');
if(cwd!==process.env.FIREFLY_HISTORY_VERIFY_WORKSPACE||path.parse(cwd).root.toUpperCase()!=='E:\\'||!root||!path.isAbsolute(root)||!within(canonicalPath(path.join(cwd,'output','memory-h')),canonicalPath(root)))throw new Error('HISTORY_PROBE_ROOT_INVALID');
const ownedRoot=root;app.disableHardwareAcceleration();app.commandLine.appendSwitch('disable-software-rasterizer');
const isolation=path.join(root,'isolation'),production=path.join(root,'synthetic-production');fs.mkdirSync(isolation,{recursive:true});fs.mkdirSync(production,{recursive:true});
const profile=resolveRuntimeProfile({argv:['--firefly-profile=test','--firefly-isolation-root='+isolation],env:{},isPackaged:app.isPackaged,productionAppData:production});applyElectronPaths(app,profile);app.setPath('temp',path.join(root,'temp'));
const storage=createStorageContext(profile),identity={providerId:'synthetic',sessionId:'history-session',messageId:'binding'};
const hash=(f:string)=>createHash('sha256').update(fs.readFileSync(f)).digest('hex');
function tree(folder:string):{name:string;hash:string}[]{return fs.readdirSync(folder,{withFileTypes:true}).sort((a,b)=>a.name.localeCompare(b.name)).flatMap(e=>{const full=path.join(folder,e.name);return e.isDirectory()?tree(full).map(f=>({...f,name:path.join(e.name,f.name)})):[{name:e.name,hash:hash(full)}]})}
let client:MemoryClient|undefined;
const open=(old=false)=>MemoryClient.open({storage,keyProtection:createWindowsKeyProtection(storage.memory.tempRoot),workerFactory:data=>new Worker(path.join(__dirname,old?'v8-worker.cjs':'worker.cjs'),{workerData:data,execArgv:[]})});
void(async()=>{try{await app.whenReady();let evidence:object;
 if(mode==='migrate'||mode==='rollback'){
  const manifest=JSON.parse(fs.readFileSync(path.join(__dirname,'v8-manifest.json'),'utf8'));assert.equal(hash(path.join(__dirname,'v8-writer.cjs')),manifest.hashes['v8-writer.cjs']);
  client=await open(true);await client.writeBatch({scopeKey:'scope-a',commandId:'native-actual-v8',records:[{table:'sources',id:'native-actual-v8-source',revision:1,payload:{text:'ACTUAL_V8_NATIVE_SYNTHETIC_RECORD'}}]});await client.close();client=undefined;
  const database=path.join(storage.memory.dataRoot,'memory.sqlite'),beforeDb=new DatabaseSync(database),cipher=beforeDb.prepare("SELECT payload FROM sources WHERE id='native-actual-v8-source'").get()?.payload;assert.equal(beforeDb.prepare('PRAGMA user_version').get()?.user_version,8);beforeDb.close();
  const backup=path.join(ownedRoot,'complete-v8-profile-backup');fs.cpSync(isolation,backup,{recursive:true});const backupProof=tree(backup);assert.ok(backupProof.some(f=>f.name.endsWith('memory.sqlite.auth')));assert.ok(backupProof.some(f=>f.name.includes('key')));
  client=await open();assert.deepEqual((await client.readRows('sources','scope-a'))[0].payload,{text:'ACTUAL_V8_NATIVE_SYNTHETIC_RECORD'});await client.close();client=undefined;
  const migrated=new DatabaseSync(database);assert.equal(migrated.prepare('PRAGMA user_version').get()?.user_version,9);assert.deepEqual(migrated.prepare("SELECT payload FROM sources WHERE id='native-actual-v8-source'").get()?.payload,cipher);migrated.close();
  if(mode==='rollback'){
   const protectedBefore=['memory.sqlite','memory.sqlite.auth'].map(n=>({name:n,hash:hash(path.join(storage.memory.dataRoot,n))}));let oldFailure='';
   await assert.rejects(MemoryClient.open({storage,keyProtection:createWindowsKeyProtection(storage.memory.tempRoot),workerFactory:data=>{const worker=new Worker(path.join(__dirname,'v8-worker.cjs'),{workerData:data,execArgv:[]});worker.on('error',e=>{oldFailure=e.message});return worker}}));assert.equal(oldFailure,'MEMORY_SCHEMA_UNSUPPORTED');assert.deepEqual(['memory.sqlite','memory.sqlite.auth'].map(n=>({name:n,hash:hash(path.join(storage.memory.dataRoot,n))})),protectedBefore);
   // Restore only our verified owned synthetic root, after all writers closed.
   assert.ok(within(canonicalPath(ownedRoot),canonicalPath(isolation)));assert.equal(path.dirname(isolation),ownedRoot);fs.rmSync(isolation,{recursive:true,force:true});fs.cpSync(backup,isolation,{recursive:true});assert.deepEqual(tree(isolation),backupProof);
   client=await open(true);assert.deepEqual((await client.readRows('sources','scope-a'))[0].payload,{text:'ACTUAL_V8_NATIVE_SYNTHETIC_RECORD'});await client.close();client=undefined;const restored=new DatabaseSync(database);assert.equal(restored.prepare('PRAGMA user_version').get()?.user_version,8);restored.close();
  }evidence={actualV8Writer:true,migratedVersion:9,encryptedSourceUnchanged:true,completeDbAuthProtectedKeyProfileBackup:true,restoredActualOldWriter:mode==='rollback'};
 }else{
  client=await open();const active=client,authority=createMainActorAuthority({resolveActor:()=> 'actor-a'}),registry=createMainSourceRegistry(active,{coordinate:authority.coordinate}),provider=new SyntheticSourceProvider(path.join(ownedRoot,'synthetic-provider.json'),'scope-a'),access=registry.authority.access('scope-a'),actor=authority.bindActor(access,provider.adapter,identity),history=createMainHistory({actorAuthority:authority,registry,transport:active}),migration=createHistoryMigration({actorAuthority:authority,transport:active});
  const framing={providerId:'synthetic',model:'fixture',transport:'synthetic',framingVersion:'v1'},prepare=(units:any[])=>({...framing,inputTypes:['text'],body:{messages:units.flatMap(u=>u.messages)}}),context=createMainContext({actorAuthority:authority,registry,transport:active,counter:{capability:{...framing,mode:'exact',inputTypes:['text']},count:async(r:any)=>JSON.stringify(r.body).length},budget:{maxContextTokens:20000,reservedOutputTokens:64,safetyMarginTokens:16,maxSTokens:16000,minRecentCompleteTurns:0},prepare,prepareS:prepare});
  const exported={format:'firefly-history-synthetic-v1',records:[{sourceId:'native-import-1',sourceProvider:'synthetic',sourceSession:identity.sessionId,revision:1,incarnation:'original-1',messages:[{id:'user1',role:'user',text:'cat native imported evidence',occurredAt:1000,timeZone:'Asia/Shanghai'}]}]};
  if(mode==='create'){
   const id={...identity,messageId:'native-source'};provider.write(id,{text:'cat native canonical evidence',role:'user',trust:'direct-user-event',occurredAt:500});const ref=await registry.capture(access,provider.adapter,id),document={documentId:'native-document',incarnation:'native-1',revision:1};await history.captureSource(actor,ref,document);
   const q=await history.query(actor,{query:'cat'});assert.equal(q.hits.length,1);const snapshot=await context.assemble(actor,{sessionId:identity.sessionId,sourceRefs:[],historyTokens:[q.evidence]}),permit=await context.validateForDispatch(actor,snapshot);await history.remove(actor,{documentId:document.documentId,revision:document.revision});let sends=0;await assert.rejects(context.dispatch(actor,permit,()=>{sends++;return 'bad'}),/MEMORY_HISTORY_STALE/);assert.equal(sends,0);
   await history.captureSource(actor,ref,{...document,incarnation:'native-2',revision:2});const fresh=await history.query(actor,{query:'cat'}),s=await context.assemble(actor,{sessionId:identity.sessionId,sourceRefs:[],historyTokens:[fresh.evidence]});assert.equal((await context.dispatch(actor,await context.validateForDispatch(actor,s),()=>{sends++;return 'local-success'})).status,'sent');assert.equal(sends,1);
   let transcript:any={id:'native-tool-turn',incarnation:'v1',revision:1,origin:'canonical',sourceDeps:[{sourceRef:ref,subjectKeys:null,derivedRefs:null}],vector:null,messages:[{id:'u',role:'user',text:'cat native canonical evidence',occurredAt:500,timeZone:null,sourceRef:ref},{id:'a',role:'assistant',text:'tool probe cat',occurredAt:null,timeZone:null,toolCallIds:['t']},{id:'t',role:'tool',text:'tool probe OLD',occurredAt:null,timeZone:null,toolCallId:'t'}]},historyProvider=createMainHistoryProvider(authority,actor,{withLease:async(_id,run)=>run(async()=>structuredClone(transcript))});await history.captureTranscript(actor,historyProvider,'native-tool-turn');const tq=await history.query(actor,{query:'tool probe'}),ts=await context.assemble(actor,{sessionId:identity.sessionId,sourceRefs:[],historyTokens:[tq.evidence]}),tp=await context.validateForDispatch(actor,ts);transcript={...transcript,revision:2,messages:transcript.messages.map((m:any)=>m.id==='t'?{...m,text:'tool probe NEW'}:m)};await assert.rejects(context.dispatch(actor,tp,()=>{sends++;return 'bad'}),/MEMORY_HISTORY_STALE/);assert.equal(sends,1);const captured=await history.captureTranscript(actor,historyProvider,'native-tool-turn');await history.prepareTranscriptChange(actor,captured.transcriptToken);assert.ok(!(await history.query(actor,{query:'tool probe'})).hits.some(h=>h.document.id==='native-tool-turn'));await history.remove(actor,{documentId:'native-tool-turn',revision:2});
   const preview=await migration.preview(actor,exported);await assert.rejects(migration.apply(actor,preview.ticket),/MEMORY_HISTORY_APPLY_DENIED/);assert.equal((await migration.apply(actor,migration.authorizeApply(actor,preview.ticket))).inserted,1);assert.equal((await active.current('scope-a')).length,0);assert.equal((await history.query(actor,{query:'cat'})).hits.length,2);evidence={canonicalAndImported:2,staleSendBlocked:true,editedUnsourcedToolSendBlocked:true,transcriptPendingBlocksIndex:true,localInvocations:1,previewCannotApply:true,noMSupport:true};
  }else if(mode==='reopen'){
   const q=await history.query(actor,{query:'cat'});assert.equal(q.hits.length,2);const preview=await migration.preview(actor,exported);assert.equal(preview.report.duplicates,1);assert.equal((await migration.apply(actor,migration.authorizeApply(actor,preview.ticket))).duplicates,1);
   const policy=createMainPolicy({registry,transport:active,resolveActor:()=> 'actor-a',actorAuthority:authority}),id={...identity,messageId:'forget-root'};provider.write(id,{text:'I prefer bash',role:'user',trust:'direct-user-event'});const ref=await registry.capture(access,provider.adapter,id),fact=await policy.ingest(actor,ref);await policy.act(actor,await policy.event(actor,{kind:'forget',nonce:randomUUID(),factId:fact.factId,revision:1}));assert.equal((await history.query(actor,{query:'cat'})).hits.length,0);await assert.rejects(context.assemble(actor,{sessionId:identity.sessionId,sourceRefs:[],historyTokens:[q.evidence]}),/MEMORY_HISTORY_STALE/);evidence={reopened:2,importDuplicate:1,forgetBlocksOldHistory:true};
  }else throw new Error('HISTORY_PROBE_MODE_INVALID');await client.close();client=undefined;
 }
 const result={ok:true,mode,packaged:app.isPackaged,versions:{electron:process.versions.electron,node:process.versions.node,sqlite:process.versions.sqlite,jieba:require('@node-rs/jieba/package.json').version},syntheticCounter:true,...evidence};fs.writeFileSync(path.join(ownedRoot,'result-'+mode+'.json'),JSON.stringify(result));console.log(JSON.stringify(result));app.exit(0);
}catch(e){await client?.close().catch(()=>{});fs.writeFileSync(path.join(ownedRoot,'result-'+mode+'.json'),JSON.stringify({ok:false,error:e instanceof Error?e.message:'HISTORY_PROBE_FAILED'}));app.exit(1)}})();
