import assert from "node:assert/strict";
import {MemoryService} from "../../../src/main/memory-core/memory-service";
import {createMainMemoryAuthority,type VerifiedSource} from "../../../src/main/memory-core/main-access";
import type {MemoryClient} from "../../../src/main/memory-core/worker-client";
export async function verifyJobs(client:MemoryClient,canary:string){
 const sources=new Map<string,VerifiedSource>(),ref={sourceId:"jobs-source",revision:1},scopeKey="jobs-scope";
 sources.set(ref.sourceId,{...ref,scopeKey,kind:"user",intent:"statement",policyEligibility:{directStatement:true,inferred:false,sensitive:false,conflict:false}});
 const authority=createMainMemoryAuthority({policyVersion:"policy-v1",resolveSource:r=>sources.get(r.sourceId)!}),access=authority.access(scopeKey),service=new MemoryService(client);
 const fact={subjectKey:"\u5408\u6210\u53cc\u8bed",assertion:canary,assertionKind:"user-statement" as const,time:{validFrom:null,validTo:null,referenceTime:null}};
 await service.registerSource(access,"jobs-register",ref);
 await service.enqueueJob(access,{commandId:"jobs-enqueue",jobId:"job-current",sourceRef:ref});
 const competing=await Promise.allSettled([0,1].map(n=>service.claimJob(access,{commandId:"jobs-claim-"+n,jobId:"job-current",leaseMs:60000})));
 assert.equal(competing.filter(r=>r.status==="fulfilled").length,1);
 assert.equal((competing.find(r=>r.status==="rejected") as PromiseRejectedResult).reason.message,"MEMORY_JOB_BUSY");
 const lease=(competing.find(r=>r.status==="fulfilled") as PromiseFulfilledResult<{leaseToken:string}>).value;
 const input={commandId:"jobs-result",jobId:"job-current",leaseToken:lease.leaseToken,proposals:[{candidateId:"job-candidate",evidenceId:"job-evidence",text:canary,fact}]};
 assert.deepEqual(await service.commitJobResult(access,input),await service.commitJobResult(access,input));
 assert.equal((await client.readRows("candidates",scopeKey)).length,1);assert.equal((await service.current(access)).length,0);
 await assert.rejects(service.commitJobResult(access,{...input,proposals:[{...input.proposals[0],text:canary+" changed"}]}),/MEMORY_COMMAND_CONFLICT/);
 await assert.rejects(service.current(JSON.parse(JSON.stringify(access))),/MEMORY_ACCESS_DENIED/);
 assert.equal((await service.current(authority.access("other-scope"))).length,0);
 const token=authority.authorize(access,{candidateId:"job-candidate",sourceRef:ref,reason:"policyAccepted"});
 const active=await service.activateCandidate(access,token,{commandId:"jobs-activate",candidateId:"job-candidate"});
 for(const id of ["queued","running","edited"])await service.enqueueJob(access,{commandId:"enqueue-"+id,jobId:id,sourceRef:ref});
 const running=await service.claimJob(access,{commandId:"claim-running",jobId:"running",leaseMs:60000});
 const edited=await service.claimJob(access,{commandId:"claim-edited",jobId:"edited",leaseMs:60000});
 sources.set(ref.sourceId,{...sources.get(ref.sourceId)!,revision:2});
 await service.registerSource(access,"jobs-source-edit",{...ref,revision:2});
 await assert.rejects(service.commitJobResult(access,{...input,commandId:"edited-result",jobId:"edited",leaseToken:edited.leaseToken}),/MEMORY_JOB_SOURCE_STALE/);
 const forgetting={sourceId:"jobs-forget",revision:1};
 sources.set(forgetting.sourceId,{...forgetting,scopeKey,kind:"user",intent:"forget",factId:active.id});
 await service.registerSource(access,"jobs-forget-register",forgetting);
 await service.forgetFact(access,{commandId:"jobs-forget",factId:active.id,expectedRevision:1,sourceRef:forgetting});
 assert.equal((await service.current(access)).length,0);
 await assert.rejects(service.claimJob(access,{commandId:"late-claim",jobId:"queued",leaseMs:60000}),/MEMORY_JOB_SUPPRESSED/);
 await assert.rejects(service.commitJobResult(access,{...input,commandId:"late-running",jobId:"running",leaseToken:running.leaseToken}),/MEMORY_JOB_SUPPRESSED/);
 const remember={sourceId:"jobs-remember",revision:1};
 sources.set(remember.sourceId,{...remember,scopeKey,kind:"user",intent:"remember",candidateId:"remember-candidate"});
 await service.registerSource(access,"remember-register",remember);
 await service.appendEvidence(access,{commandId:"remember-evidence",evidenceId:"remember-evidence",sourceRef:remember,text:canary});
 await service.proposeCandidate(access,{commandId:"remember-candidate",candidateId:"remember-candidate",evidenceId:"remember-evidence",fact});
 const confirmed=authority.authorize(access,{candidateId:"remember-candidate",sourceRef:remember,reason:"explicitUserConfirmed"});
 await service.activateCandidate(access,confirmed,{commandId:"remember-activate",candidateId:"remember-candidate"});
 const current=await service.current(access);
 assert.equal(current.length,1);assert.equal(current[0].assertion,canary);assert.equal(current[0].activationReason,"explicitUserConfirmed");
 assert.equal((await client.readRows("deletion_markers",scopeKey)).length,1);
 await assert.rejects(service.commitJobResult(access,{...input,commandId:"late-after-remember",jobId:"running",leaseToken:running.leaseToken}),/MEMORY_JOB_SUPPRESSED/);
 await service.enqueueJob(access,{commandId:"new-generation",jobId:"new-generation",sourceRef:remember});
 const next=await service.claimJob(access,{commandId:"new-generation-claim",jobId:"new-generation",leaseMs:60000});
 assert.ok(next.suppressionGeneration>running.suppressionGeneration);
 return {jobReplay:true,competingClaims:true,changedReplayRejected:true,sourceRevisionBarrier:true,forgetBarrier:true,rememberGeneration:true,oldJobStillBlocked:true,trustedScope:true,canaryMatch:true};
}
