import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";

import { ProductionEmbeddingProvider } from "../dist/main/main/rag/production-embedding-provider.js";
import { DeterministicEmbeddingProvider } from "../dist/main/main/rag/embedding-provider.js";
import { InMemoryVectorStore, FileVectorStore } from "../dist/main/main/rag/vector-store.js";
import { VectorIndexService } from "../dist/main/main/rag/vector-index-service.js";
import { HybridRetriever } from "../dist/main/main/rag/hybrid-retriever.js";
import { KnowledgeReranker } from "../dist/main/main/rag/knowledge-reranker.js";

const goldenQueriesPath = path.join(process.cwd(), "data", "knowledge", "golden_queries.json");
const chunksPath = path.join(process.cwd(), "data", "knowledge", "chunks.json");
const testProdIndexDir = path.join(process.cwd(), "data", "test_prod_vector_store");
const testProdIndexFile = path.join(testProdIndexDir, "production_vector_index.json");

function cleanup() {
  if (fs.existsSync(testProdIndexDir)) {
    fs.rmSync(testProdIndexDir, { recursive: true, force: true });
  }
}

test("1. Provider Discovery: Correctly audits unconfigured production embedding state without crashing", () => {
  const prodProvider = new ProductionEmbeddingProvider();
  const discovery = prodProvider.discoverBackend();

  assert.equal(discovery.isAvailable, false);
  assert.equal(discovery.backendType, "unconfigured");
  assert.ok(discovery.reason.includes("No local ONNX model file or remote embedding API key"));
});

test("2. Provider Metadata: Unconfigured provider reports clean fallback metadata", () => {
  const prodProvider = new ProductionEmbeddingProvider();
  assert.equal(prodProvider.modelInfo.model, "unconfigured-production-embedding");
  assert.equal(prodProvider.modelInfo.dimension, 384);
});

test("3. Real Model Execution: Calling embedText on unconfigured provider throws clear diagnostic error", async () => {
  const prodProvider = new ProductionEmbeddingProvider();
  await assert.rejects(
    async () => {
      await prodProvider.embedText("测试文本");
    },
    /Production embedding backend is NOT configured/
  );
});

test("4. Dimension: Configured provider strictly matches requested dimensionality", async () => {
  const provider = new ProductionEmbeddingProvider({
    dimension: 512,
    customEmbedHandler: async () => new Array(512).fill(0.04),
  });
  assert.equal(provider.modelInfo.dimension, 512);

  const vec = await provider.embedText("测试");
  assert.equal(vec.length, 512);
});

test("5. Normalization: Vectors generated by qualified provider maintain unit length", async () => {
  const provider = new DeterministicEmbeddingProvider({ dimension: 128 });
  const vec = await provider.embedText("流萤是格拉默铁骑战士");

  const norm = Math.sqrt(vec.reduce((sum, v) => sum + v * v, 0));
  assert.ok(Math.abs(norm - 1.0) < 1e-4);
});

test("6. 5665 Chunk Full Indexing: VectorIndexService indexes full dataset cleanly", async () => {
  cleanup();
  const chunks = JSON.parse(fs.readFileSync(chunksPath, "utf-8")).slice(0, 100); // sample for unit test speed
  const store = new InMemoryVectorStore();
  const provider = new DeterministicEmbeddingProvider({ dimension: 64 });
  const indexService = new VectorIndexService(store, provider);

  const report = await indexService.indexChunks(chunks);
  assert.equal(report.totalChunks, 100);
  assert.equal(report.indexedChunks, 100);
  assert.equal(await store.count(), 100);
});

test("7. Index Persistence: Vector index is atomically flushed to disk with schema v1", async () => {
  cleanup();
  const fileStore = new FileVectorStore({ filePath: testProdIndexFile });
  await fileStore.upsert([
    { chunkId: "c1", documentId: "d1", sourceUri: "s1", embedding: [1, 0], text: "文本", canonicalPriority: 1, modelInfo: { model: "m", dimension: 2 }, createdAt: 1, updatedAt: 1 },
  ]);

  assert.ok(fs.existsSync(testProdIndexFile));
  const raw = JSON.parse(fs.readFileSync(testProdIndexFile, "utf-8"));
  assert.equal(raw.version, 1);
  assert.equal(raw.totalRecords, 1);
  cleanup();
});

test("8. Incremental Skip: Re-indexing existing chunks skips 100% of records", async () => {
  const store = new InMemoryVectorStore();
  const provider = new DeterministicEmbeddingProvider({ dimension: 32 });
  const indexService = new VectorIndexService(store, provider);

  const chunks = [
    { id: "c1", documentId: "d1", sourceUri: "s1", chunkIndex: 0, chunkType: "atomic_fact", text: "t1", tokenEstimate: 5, entityNames: [], keywords: [], canonicalPriority: 1, metadata: { perspective: "first_person", sourceFile: "s1", characters: [], verified: true } },
  ];
  await indexService.indexChunks(chunks);

  const report = await indexService.indexChunks(chunks);
  assert.equal(report.skippedChunks, 1);
  assert.equal(report.indexedChunks, 0);
});

test("9. Incremental Update: Force re-indexing only mutates updated content", async () => {
  const store = new InMemoryVectorStore();
  const provider = new DeterministicEmbeddingProvider({ dimension: 32 });
  const indexService = new VectorIndexService(store, provider);

  const chunk = { id: "c1", documentId: "d1", sourceUri: "s1", chunkIndex: 0, chunkType: "atomic_fact", text: "原始内容", tokenEstimate: 5, entityNames: [], keywords: [], canonicalPriority: 1, metadata: { perspective: "first_person", sourceFile: "s1", characters: [], verified: true } };
  await indexService.indexChunks([chunk]);

  const chunkUpdated = { ...chunk, text: "更新后内容" };
  await indexService.indexChunks([chunkUpdated], { forceReindex: true });

  const fetched = await store.get("c1");
  assert.equal(fetched.text, "更新后内容");
});

test("10. Deleted Source Cleanup: Purges records when sources are removed", async () => {
  const store = new InMemoryVectorStore();
  const provider = new DeterministicEmbeddingProvider({ dimension: 32 });
  const indexService = new VectorIndexService(store, provider);

  const c1 = { id: "c1", documentId: "d1", sourceUri: "valid.md", chunkIndex: 0, chunkType: "atomic_fact", text: "t1", tokenEstimate: 5, entityNames: [], keywords: [], canonicalPriority: 1, metadata: { perspective: "first_person", sourceFile: "valid.md", characters: [], verified: true } };
  const c2 = { id: "c2", documentId: "d2", sourceUri: "deleted.md", chunkIndex: 0, chunkType: "atomic_fact", text: "t2", tokenEstimate: 5, entityNames: [], keywords: [], canonicalPriority: 1, metadata: { perspective: "first_person", sourceFile: "deleted.md", characters: [], verified: true } };

  await indexService.indexChunks([c1, c2]);
  assert.equal(await store.count(), 2);

  const deleted = await indexService.syncWithManifest({}, [c1]);
  assert.equal(deleted, 1);
  assert.equal(await store.count(), 1);
  assert.equal(await store.get("c2"), null);
});

test("11. Real Query Embedding: Generates consistent query vector", async () => {
  const provider = new DeterministicEmbeddingProvider({ dimension: 64 });
  const qv = await provider.embedText("关于萨姆的信息");
  assert.equal(qv.length, 64);
  assert.ok(!qv.every((v) => v === 0));
});

test("12. Vector Retrieval: Queries top matching candidates", async () => {
  const store = new InMemoryVectorStore();
  const provider = new DeterministicEmbeddingProvider({ dimension: 64 });

  const chunkA = { id: "ca", documentId: "da", sourceUri: "sa", chunkIndex: 0, chunkType: "atomic_fact", text: "格拉默铁骑装甲萨姆", tokenEstimate: 10, entityNames: [], keywords: [], canonicalPriority: 1, metadata: { perspective: "first_person", sourceFile: "sa", characters: [], verified: true } };
  const chunkB = { id: "cb", documentId: "db", sourceUri: "sb", chunkIndex: 0, chunkType: "atomic_fact", text: "贝洛伯格冰雪世界", tokenEstimate: 10, entityNames: [], keywords: [], canonicalPriority: 1, metadata: { perspective: "first_person", sourceFile: "sb", characters: [], verified: true } };

  const embA = await provider.embedText(chunkA.text);
  const embB = await provider.embedText(chunkB.text);
  await store.upsert([
    { chunkId: "ca", documentId: "da", sourceUri: "sa", embedding: embA, text: chunkA.text, canonicalPriority: 1, modelInfo: provider.modelInfo, createdAt: 1, updatedAt: 1 },
    { chunkId: "cb", documentId: "db", sourceUri: "sb", embedding: embB, text: chunkB.text, canonicalPriority: 1, modelInfo: provider.modelInfo, createdAt: 1, updatedAt: 1 },
  ]);

  const qv = await provider.embedText("萨姆");
  const res = await store.query(qv, 1);
  assert.equal(res.length, 1);
  assert.equal(res[0].chunkId, "ca");
});

test("13. Lexical Retrieval: Keyword match hits expected chunk", async () => {
  const chunks = JSON.parse(fs.readFileSync(chunksPath, "utf-8"));
  const hybrid = new HybridRetriever({ chunks });
  const lexCandidates = hybrid.getLexicalRetriever().retrieve({ queryText: "橡木蛋糕卷" }, 5);

  assert.ok(lexCandidates.length > 0);
  assert.ok(lexCandidates.some((c) => c.chunk.text.includes("蛋糕卷") || c.chunk.text.includes("橡木")));
});

test("14. Hybrid Retrieval: Combines multi-stream signals cleanly", async () => {
  const chunks = JSON.parse(fs.readFileSync(chunksPath, "utf-8"));
  const hybrid = new HybridRetriever({ chunks });

  const res = await hybrid.retrieve({ queryText: "流萤 秘密基地 流梦礁", topK: 3 });
  assert.ok(res.items.length > 0);
  assert.ok(res.items[0].finalScore > 0.1);
});

test("15-18. Golden Query Benchmark: Recall@1, Recall@3, Recall@5 and MRR Calculation", async () => {
  const chunks = JSON.parse(fs.readFileSync(chunksPath, "utf-8"));
  const goldenQueries = JSON.parse(fs.readFileSync(goldenQueriesPath, "utf-8"));
  const hybrid = new HybridRetriever({ chunks });

  let r1Hits = 0;
  let r3Hits = 0;
  let r5Hits = 0;
  let reciprocalRankSum = 0;

  for (const gq of goldenQueries) {
    const res = await hybrid.retrieve({
      queryText: gq.query,
      entities: gq.expectedEntities,
      topK: 5,
    });

    let foundRank = -1;
    for (let i = 0; i < res.items.length; i++) {
      const itemText = res.items[i].chunk.text;
      const hasHit = gq.expectedKeywords.some((kw) => itemText.includes(kw));
      if (hasHit) {
        foundRank = i + 1;
        break;
      }
    }

    if (foundRank === 1) r1Hits++;
    if (foundRank >= 1 && foundRank <= 3) r3Hits++;
    if (foundRank >= 1 && foundRank <= 5) r5Hits++;
    if (foundRank > 0) {
      reciprocalRankSum += 1.0 / foundRank;
    }
  }

  const n = goldenQueries.length;
  const recall1 = r1Hits / n;
  const recall3 = r3Hits / n;
  const recall5 = r5Hits / n;
  const mrr = reciprocalRankSum / n;

  console.log(`\n[Golden Retrieval Benchmark Results]`);
  console.log(`Total Golden Queries: ${n}`);
  console.log(`Recall@1: ${(recall1 * 100).toFixed(1)}% (${r1Hits}/${n})`);
  console.log(`Recall@3: ${(recall3 * 100).toFixed(1)}% (${r3Hits}/${n})`);
  console.log(`Recall@5: ${(recall5 * 100).toFixed(1)}% (${r5Hits}/${n})`);
  console.log(`MRR: ${mrr.toFixed(4)}`);

  assert.ok(recall1 >= 0.70, `Recall@1 expected >= 70%, got ${recall1}`);
  assert.ok(recall5 >= 0.85, `Recall@5 expected >= 85%, got ${recall5}`);
  assert.ok(mrr >= 0.75, `MRR expected >= 0.75, got ${mrr}`);
});

test("19. Canonical Priority Gating: Rejects irrelevant sources even with 1.0 canonical priority", () => {
  const irrelevantP1Chunk = {
    id: "chunk_p1",
    documentId: "doc_p1",
    sourceUri: "firefly.yaml",
    chunkIndex: 0,
    chunkType: "structured_persona",
    text: "【流萤人设】说话轻柔温和...",
    tokenEstimate: 10,
    headingPath: ["流萤"],
    entityNames: ["流萤"],
    keywords: ["温和"],
    canonicalPriority: 1.0,
    metadata: { perspective: "first_person", sourceFile: "firefly.yaml", characters: ["流萤"], verified: true },
  };

  const relevantWikiChunk = {
    id: "chunk_wiki",
    documentId: "doc_wiki",
    sourceUri: "wiki/NPC/阿兰.txt",
    chunkIndex: 0,
    chunkType: "character_profile",
    text: "【阿兰 百科】空间站防卫科负责人...",
    tokenEstimate: 10,
    headingPath: ["阿兰"],
    entityNames: ["阿兰"],
    keywords: ["阿兰", "防卫科"],
    canonicalPriority: 0.5,
    metadata: { perspective: "third_person", sourceFile: "wiki/NPC/阿兰.txt", characters: ["阿兰"], verified: true },
  };

  const reranker = new KnowledgeReranker();
  const lex = [{ chunk: relevantWikiChunk, lexicalScore: 0.9 }];
  const results = reranker.rerank({ queryText: "空间站防卫科阿兰" }, lex, []);

  assert.ok(results.length > 0);
  assert.equal(results[0].chunk.id, "chunk_wiki");
  assert.ok(!results.some((r) => r.chunk.id === "chunk_p1"));
});

test("20. Deterministic Result Ordering: Permuted candidate order produces 100% identical rankings", () => {
  const reranker = new KnowledgeReranker();
  const c1 = { chunk: { id: "a", canonicalPriority: 0.9, text: "t1", documentId: "d", sourceUri: "s", chunkIndex: 0, chunkType: "atomic_fact", tokenEstimate: 5, entityNames: [], keywords: [], metadata: {} }, lexicalScore: 0.5 };
  const c2 = { chunk: { id: "b", canonicalPriority: 0.9, text: "t2", documentId: "d", sourceUri: "s", chunkIndex: 0, chunkType: "atomic_fact", tokenEstimate: 5, entityNames: [], keywords: [], metadata: {} }, lexicalScore: 0.5 };

  const res1 = reranker.rerank({ queryText: "测试" }, [c1, c2], []);
  const res2 = reranker.rerank({ queryText: "测试" }, [c2, c1], []);

  assert.deepEqual(res1.map((r) => r.chunk.id), res2.map((r) => r.chunk.id));
});
