import {afterEach,it,expect} from "vitest";
import {randomUUID} from "node:crypto";
import {recallFixture} from "../../../scripts/verify/memory-recall/recall-fixture";
import {createMainRecall} from "./main-recall";
import {DEFAULT_RECALL_POLICY} from "./recall-decay";
const fixtures:ReturnType<typeof recallFixture>[]=[];function fixture(){const f=recallFixture();fixtures.push(f);const recall=createMainRecall({actorAuthority:f.authority,transport:f.transport});return {...f,recall}}
afterEach(()=>{for(const f of fixtures.splice(0))f.close()});
const ref=(a:any)=>({factId:a.factId,revision:1});const DAY=86400000;
async function action(f:ReturnType<typeof fixture>,a:any,kind:"archive"|"restore"|"pin"|"unpin"){const p=await f.recall.preview(f.actor,[ref(a)],kind);return f.recall.apply(f.actor,p)}
it("Main archive and restore change visibility without changing fact truth",async()=>{const f=fixture(),a=await f.active(),truth=await f.policy.recall(f.actor);await action(f,a,"archive");expect((await f.recall.rank(f.actor)).items).toEqual([]);expect(await f.policy.recall(f.actor)).toEqual(truth);f.advance(DAY);await action(f,a,"restore");const s=(await f.recall.metadata(f.actor,[ref(a)])).targets[0];expect(s).toMatchObject({visibility:"normal",visibilityRevision:2,lastAccessAt:null,strengthAtLastCalculation:1});expect(await f.policy.recall(f.actor)).toEqual(truth)});
it("Main pin and unpin never claim confirmation or actual access",async()=>{const f=fixture(),a=await f.active();await action(f,a,"pin");const first=(await f.recall.rank(f.actor)).items[0];expect(first.protection).toEqual({pinned:true,explicitConfirmation:false,required:false});expect(first.state.lastAccessAt).toBeNull();await action(f,a,"unpin");expect((await f.recall.rank(f.actor)).items[0].state.pinned).toBe(false)});
it("fake preview and another factory preview cannot mutate",async()=>{const f=fixture(),a=await f.active(),other=createMainRecall({actorAuthority:f.authority,transport:f.transport});await expect(f.recall.apply(f.actor,{})).rejects.toThrow("MEMORY_RECALL_PREVIEW_DENIED");await expect(f.recall.apply(f.actor,await other.preview(f.actor,[ref(a)],"archive"))).rejects.toThrow("MEMORY_RECALL_PREVIEW_DENIED")});
it("fake and temporary actors fail before Worker commands",async()=>{const f=fixture(),before=f.commands.length;await expect(f.recall.rank({})).rejects.toThrow("MEMORY_ACTOR_DENIED");const temporary=f.authority.bindActor(f.access,f.provider.adapter,f.identity,{sessionMode:"temporary"});await expect(f.recall.rank(temporary)).rejects.toThrow("MEMORY_RECALL_TEMPORARY_UNSUPPORTED");expect(f.commands).toHaveLength(before)});
it("preview is single use but Worker receipt retry is idempotent",async()=>{const f=fixture(),a=await f.active(),preview=await f.recall.preview(f.actor,[ref(a)],"archive");await f.recall.apply(f.actor,preview);await expect(f.recall.apply(f.actor,preview)).rejects.toThrow("MEMORY_RECALL_PREVIEW_USED");const command=f.commands.at(-1);expect(await f.transport.recallCommand(command)).toEqual({changed:1});expect((await f.recall.metadata(f.actor,[ref(a)])).targets[0].visibilityRevision).toBe(1)});
it("expired preview is rejected without changing visibility",async()=>{const f=fixture(),a=await f.active(),preview=await f.recall.preview(f.actor,[ref(a)],"archive");f.advance(60001);await expect(f.recall.apply(f.actor,preview)).rejects.toThrow("MEMORY_RECALL_PREVIEW_EXPIRED");expect((await f.recall.rank(f.actor)).items).toHaveLength(1)});
it("forgotten fact cannot be restored or recreate memory through old preview",async()=>{const f=fixture(),a=await f.active();await action(f,a,"archive");const preview=await f.recall.preview(f.actor,[ref(a)],"restore");await f.policy.act(f.actor,await f.policy.event(f.actor,{kind:"forget",nonce:randomUUID(),...ref(a)}));await expect(f.recall.apply(f.actor,preview)).rejects.toThrow("MEMORY_RECALL_STALE");await expect(f.recall.preview(f.actor,[ref(a)],"restore")).rejects.toThrow("MEMORY_RECALL_FACT_UNAVAILABLE");expect(await f.policy.recall(f.actor)).toEqual([])});
it("last support invalidation dominates archived restore",async()=>{const f=fixture(),a=await f.active();await action(f,a,"archive");const p=await f.recall.preview(f.actor,[ref(a)],"restore");await f.registry.prepareChange(f.access,f.provider.adapter,a.ref);await expect(f.recall.apply(f.actor,p)).rejects.toThrow("MEMORY_RECALL_FACT_UNAVAILABLE")});
it("another valid support permits an explicit restore",async()=>{const f=fixture(),a=await f.active();await f.active("我默认用 Bash");await action(f,a,"archive");await f.registry.prepareChange(f.access,f.provider.adapter,a.ref);await action(f,a,"restore");expect((await f.recall.rank(f.actor)).items).toHaveLength(1)});
it("corrected revision cannot be modified with old preview",async()=>{const f=fixture(),a=await f.active(),p=await f.recall.preview(f.actor,[ref(a)],"archive"),s=await f.source("I prefer powershell");await f.policy.act(f.actor,await f.policy.event(f.actor,{kind:"correct",nonce:randomUUID(),...ref(a),sourceRef:s.ref}));await expect(f.recall.apply(f.actor,p)).rejects.toThrow("MEMORY_RECALL_FACT_UNAVAILABLE");expect((await f.recall.rank(f.actor)).items[0].state.factRevision).toBe(2)});
it("policy and intervening projection changes invalidate preview",async()=>{const f=fixture(),a=await f.active(),p=await f.recall.preview(f.actor,[ref(a)],"archive");await f.recall.configure(f.actor,{...DEFAULT_RECALL_POLICY,version:"v2"});await expect(f.recall.apply(f.actor,p)).rejects.toThrow("MEMORY_RECALL_STALE")});
it("transaction fault leaves visibility and receipt unchanged",async()=>{const f=fixture(),a=await f.active(),p=await f.recall.preview(f.actor,[ref(a)],"archive");f.setFault("commit");await expect(f.recall.apply(f.actor,p)).rejects.toThrow("MEMORY_RECALL_INJECTED_FAULT");f.setFault("");expect((await f.recall.rank(f.actor)).items).toHaveLength(1)});
it("default dry run reports candidates without actual access or archive",async()=>{const f=fixture(),a=await f.active();await f.recall.rank(f.actor);f.advance(90*DAY);expect(await f.recall.maintain(f.actor)).toMatchObject({mode:"dry-run",candidates:1,archived:0});expect((await f.recall.metadata(f.actor,[ref(a)])).targets[0]).toMatchObject({visibility:"normal",lastAccessAt:null})});
it("enabled trusted maintenance archives aged facts in bounded batches",async()=>{const f=fixture();await f.active();await f.active("I prefer English");await f.active("I prefer concise responses");await f.recall.configure(f.actor,{...DEFAULT_RECALL_POLICY,version:"enabled",maintenanceMode:"enabled",batchSize:1});await f.recall.rank(f.actor);f.advance(90*DAY);expect(await f.recall.maintain(f.actor)).toMatchObject({archived:3,batches:3});expect((await f.recall.rank(f.actor)).items).toEqual([]);expect((await f.recall.maintain(f.actor)).archived).toBe(0)});
it("maintenance protects Main pin, valid independent confirmation and required facts",async()=>{const f=fixture(),a=await f.active(),b=await f.active("I prefer English"),c=await f.active("I prefer concise responses");await action(f,a,"pin");const independent=await f.source("I prefer English");await f.policy.act(f.actor,await f.policy.event(f.actor,{kind:"confirmFact",nonce:randomUUID(),...ref(b),sourceRef:independent.ref}));await f.recall.configure(f.actor,{...DEFAULT_RECALL_POLICY,version:"enabled",maintenanceMode:"enabled"});await f.recall.rank(f.actor);f.advance(90*DAY);expect((await f.recall.maintain(f.actor,{requiredFactRefs:[ref(c)]})).archived).toBe(0);expect((await f.recall.rank(f.actor)).items).toHaveLength(3)});
it("disabled and pre-cancelled maintenance make no archive",async()=>{const f=fixture();await f.active();await f.recall.rank(f.actor);f.advance(90*DAY);await f.recall.configure(f.actor,{...DEFAULT_RECALL_POLICY,version:"disabled",maintenanceMode:"disabled"});expect((await f.recall.maintain(f.actor)).archived).toBe(0);const controller=new AbortController();controller.abort();expect(await f.recall.maintain(f.actor,{signal:controller.signal})).toMatchObject({cancelled:true,archived:0})});
it("maintenance cancellation between batches leaves the remaining facts visible",async()=>{const f=fixture(),controller=new AbortController();await f.active();await f.active("I prefer English");await f.recall.configure(f.actor,{...DEFAULT_RECALL_POLICY,version:"enabled",maintenanceMode:"enabled",batchSize:1});await f.recall.rank(f.actor);f.advance(90*DAY);expect(await f.recall.maintain(f.actor,{signal:controller.signal,onBatch:()=>controller.abort()})).toMatchObject({cancelled:true,archived:1,batches:1});expect((await f.recall.rank(f.actor)).items).toHaveLength(1)});
