import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import {createHash} from "node:crypto";
import {afterEach,it,expect} from "vitest";
import {DatabaseSync} from "node:sqlite";
import {openMemoryRepository} from "../memory-core/repository";
const roots:string[]=[];afterEach(()=>{for(const root of roots.splice(0))fs.rmSync(root,{recursive:true,force:true})});
function fixture(){const root=fs.mkdtempSync(path.join(os.tmpdir(),"recall-v7-"));roots.push(root);const file=path.join(root,"memory.sqlite"),source=path.join(__dirname,"fixtures/v7-writer/memory.sqlite");expect(createHash("sha256").update(fs.readFileSync(source)).digest("hex")).toBe("abe66d5aabccf0dcba143f8184b5ae41a029de9dbcabea889bfd3d17ff818434");fs.copyFileSync(source,file);fs.copyFileSync(source+".auth",file+".auth");return {root,file,key:Buffer.alloc(32,7)}}
const bytes=(root:string)=>fs.readdirSync(root).sort().map(name=>({name,bytes:fs.readFileSync(path.join(root,name))}));
it("actual old v7 writer fixture upgrades without rewriting encrypted source rows",()=>{const f=fixture(),before=new DatabaseSync(f.file);expect(before.prepare("PRAGMA user_version").get()?.user_version).toBe(7);const payload=before.prepare("SELECT payload FROM sources WHERE id='actual-v7-source'").get()?.payload;before.close();const repo=openMemoryRepository({databasePath:f.file,key:f.key});expect(repo.readRows("sources","scope-a")[0].payload).toEqual({text:"ACTUAL_V7_SYNTHETIC_RECORD"});repo.close();const db=new DatabaseSync(f.file);try{expect(db.prepare("PRAGMA user_version").get()?.user_version).toBe(9);expect(db.prepare("SELECT name FROM sqlite_master WHERE name='recall_records'").get()?.name).toBe("recall_records");expect(db.prepare("SELECT payload FROM sources WHERE id='actual-v7-source'").get()?.payload).toEqual(payload);expect(db.prepare("SELECT name FROM sqlite_master WHERE name='context_records'").get()?.name).toBe("context_records")}finally{db.close()}});
it("failed v8 migration leaves real v7 bytes and tables unchanged",()=>{const f=fixture(),db=new DatabaseSync(f.file);db.exec("CREATE INDEX recall_records_by_kind ON sources(scope_key)");db.close();const snapshot=bytes(f.root);expect(()=>{const opened=openMemoryRepository({databasePath:f.file,key:f.key});opened.close()}).toThrow();expect(bytes(f.root)).toEqual(snapshot);const check=new DatabaseSync(f.file);try{expect(check.prepare("PRAGMA user_version").get()?.user_version).toBe(7);expect(check.prepare("SELECT name FROM sqlite_master WHERE name='recall_records' AND type='table'").get()).toBeUndefined()}finally{check.close()}});
it("wrong key refuses before altering the actual v7 fixture",()=>{const f=fixture(),snapshot=bytes(f.root);expect(()=>openMemoryRepository({databasePath:f.file,key:Buffer.alloc(32,8)})).toThrow();expect(bytes(f.root)).toEqual(snapshot)});
it("future schema refuses without altering bytes",()=>{const f=fixture(),db=new DatabaseSync(f.file);db.exec("PRAGMA user_version=99");db.close();const snapshot=bytes(f.root);expect(()=>openMemoryRepository({databasePath:f.file,key:f.key})).toThrow("MEMORY_SCHEMA_UNSUPPORTED");expect(bytes(f.root)).toEqual(snapshot)});
