import {afterEach,it,expect} from "vitest";
import {randomUUID} from "node:crypto";
import {DatabaseSync} from "node:sqlite";
import {RecordCodec} from "../memory-core/record-codec";
import {createMainContext} from "../memory-context/main-context";
import {createMainActorAuthority} from "../memory-core/main-actor-authority";
import {createMainRecall} from "./main-recall";
import {recallFixture} from "../../../scripts/verify/memory-recall/recall-fixture";
import {DEFAULT_RECALL_POLICY} from "./recall-decay";
const fixtures:ReturnType<typeof recallFixture>[]=[];const ref=(a:any)=>({factId:a.factId,revision:1});
function fixture(){const f=recallFixture();fixtures.push(f);const commands:any[]=[],transport={contextCommand:async(c:any)=>{commands.push(c);return f.transport.contextCommand(c)}};
 const identity={providerId:"synthetic",model:"synthetic-model",transport:"synthetic",framingVersion:"v1"},prepare=(units:any[],facts:any[]=[])=>({...identity,inputTypes:["text"],body:{messages:units.flatMap(u=>u.messages),facts:facts.map(f=>f.assertion)}});
 const options={registry:f.registry,transport,actorAuthority:f.authority,clock:f.now,counter:{capability:{...identity,mode:"exact" as const,inputTypes:["text"]},count:async(r:any)=>JSON.stringify(r.body).length},budget:{maxContextTokens:10000,reservedOutputTokens:64,safetyMarginTokens:16,maxSTokens:5000,minRecentCompleteTurns:1},prepare,prepareS:(u:any[])=>prepare(u)};
 const context=createMainContext(options),recall=createMainRecall({actorAuthority:f.authority,transport:f.transport});
 return {...f,context,recall,options,contextCommands:commands,assemble:(a:any)=>context.assemble(f.actor,{sessionId:"session-a",sourceRefs:[],factRefs:[ref(a)]})};
}
afterEach(()=>{for(const f of fixtures.splice(0))f.close()});
async function action(f:ReturnType<typeof fixture>,a:any,kind:"archive"|"restore"){return f.recall.apply(f.actor,await f.recall.preview(f.actor,[ref(a)],kind))}
function tickets(f:ReturnType<typeof fixture>){const db=new DatabaseSync(f.databasePath,{readOnly:true});try{return db.prepare("SELECT id,payload FROM recall_records WHERE kind='use'").all().map(r=>new RecordCodec(f.key).open<any>("recall-use","scope-a",r.id as string,r.payload))}finally{db.close()}}
it("eligibility-only policy recall cannot bypass archive during context assembly",async()=>{const f=fixture(),a=await f.active();await action(f,a,"archive");expect(await f.policy.recall(f.actor)).toHaveLength(1);await expect(f.assemble(a)).rejects.toThrow("MEMORY_RECALL_FACT_ARCHIVED")});
it("archive then restore never revives an old visible snapshot or permit",async()=>{const f=fixture(),a=await f.active(),s=await f.assemble(a),p=await f.context.validateForDispatch(f.actor,s);await action(f,a,"archive");await action(f,a,"restore");let sent=0;await expect(f.context.dispatch(f.actor,p,()=>{sent++;return "bad"})).rejects.toThrow("MEMORY_RECALL_VISIBILITY_STALE");expect(sent).toBe(0);expect((await f.assemble(a)).request.body.facts).toHaveLength(1)});
it("strength scan advances projection but preserves a visible permit",async()=>{const f=fixture(),a=await f.active(),s=await f.assemble(a),p=await f.context.validateForDispatch(f.actor,s);f.advance(30*86400000);await f.recall.rank(f.actor);expect((await f.context.dispatch(f.actor,p,()=>"ok")).status).toBe("sent")});
it("local sender invocation refreshes access exactly once after pending claim",async()=>{const f=fixture(),a=await f.active(),s=await f.assemble(a),p=await f.context.validateForDispatch(f.actor,s);f.advance(86400000);let calls=0;await f.context.dispatch(f.actor,p,()=>{calls++;expect(tickets(f)[0].state).toBe("pending");return "ok"});const state=(await f.recall.metadata(f.actor,[ref(a)])).targets[0];expect(state).toMatchObject({lastAccessAt:f.now(),strengthAtLastCalculation:1,accessCount:1});expect(tickets(f)[0].state).toBe("invoked");const confirm=f.contextCommands.find(c=>c.kind==="confirmUse");expect(await f.transport.contextCommand(confirm)).toMatchObject({useStatus:"invoked",recorded:1});expect((await f.recall.metadata(f.actor,[ref(a)])).targets[0].accessCount).toBe(1);await expect(f.context.dispatch(f.actor,p,()=>{calls++;return "bad"})).rejects.toThrow("MEMORY_CONTEXT_PERMIT_USED");expect(calls).toBe(1)});
it.each(["sync","async"])("%s sender failure records invocation but returns unknown without replay",async kind=>{const f=fixture(),a=await f.active(),s=await f.assemble(a),p=await f.context.validateForDispatch(f.actor,s);let calls=0;const result=await f.context.dispatch(f.actor,p,()=>{calls++;if(kind==="sync")throw new Error("SECRET_PROVIDER_ERROR");return Promise.reject(new Error("SECRET_PROVIDER_ERROR"))});expect(result.status).toBe("result-unknown");expect(JSON.stringify(result)).not.toContain("SECRET");expect((await f.recall.metadata(f.actor,[ref(a)])).targets[0].accessCount).toBe(1);expect(tickets(f)[0].state).toBe("invoked");await expect(f.context.dispatch(f.actor,p,()=>{calls++;return "bad"})).rejects.toThrow("MEMORY_CONTEXT_PERMIT_USED");expect(calls).toBe(1)});
it("confirmation write failure never reports an unsent request or retries transport",async()=>{const f=fixture(),a=await f.active(),s=await f.assemble(a),p=await f.context.validateForDispatch(f.actor,s);f.setFault("confirmUse");let calls=0;expect(await f.context.dispatch(f.actor,p,()=>{calls++;return "local-result"})).toMatchObject({status:"result-unknown"});f.setFault("");expect(calls).toBe(1);expect((await f.recall.metadata(f.actor,[ref(a)])).targets[0]).toMatchObject({accessCount:0,lastAccessAt:null});expect(tickets(f)[0].state).toBe("unknown");await expect(f.context.dispatch(f.actor,p,()=>{calls++;return "bad"})).rejects.toThrow("MEMORY_CONTEXT_PERMIT_USED");expect(calls).toBe(1)});
it("claim fault rolls back permit and pending ticket before any invocation",async()=>{const f=fixture(),a=await f.active(),s=await f.assemble(a),p=await f.context.validateForDispatch(f.actor,s);f.setFault("claim");let calls=0;await expect(f.context.dispatch(f.actor,p,()=>{calls++;return "bad"})).rejects.toThrow("MEMORY_RECALL_INJECTED_FAULT");f.setFault("");expect(calls).toBe(0);expect(tickets(f)).toEqual([]);expect((await f.recall.metadata(f.actor,[ref(a)])).targets[0].lastAccessAt).toBeNull()});
it("uncertain claim acknowledgement stays pending until a new process marks unknown",async()=>{const f=fixture(),a=await f.active();const transport={contextCommand:async(c:any)=>{const result=await f.options.transport.contextCommand(c);if(c.kind==="claim")throw new Error("MEMORY_WORKER_FAILED");return result}},context=createMainContext({...f.options,transport});const s=await context.assemble(f.actor,{sessionId:"session-a",sourceRefs:[],factRefs:[ref(a)]}),p=await context.validateForDispatch(f.actor,s);let calls=0;await expect(context.dispatch(f.actor,p,()=>{calls++;return "bad"})).rejects.toThrow("MEMORY_WORKER_FAILED");expect(tickets(f)[0].state).toBe("pending");expect(await f.recall.recover(f.actor)).toEqual({unknown:0});f.reopen();const authority=createMainActorAuthority({resolveActor:()=>"actor-a"}),actor=authority.bindActor(f.access,f.provider.adapter,f.identity),next=createMainRecall({actorAuthority:authority,transport:f.transport});expect(await next.recover(actor)).toEqual({unknown:1});expect(await next.recover(actor)).toEqual({unknown:0});expect(tickets(f)[0].state).toBe("unknown");expect((await next.metadata(actor,[ref(a)])).targets[0].lastAccessAt).toBeNull();expect(calls).toBe(0);const confirm=f.contextCommands.find(c=>c.kind==="claim");await expect(f.transport.contextCommand({kind:"confirmUse",scopeKey:"scope-a",body:{actorKey:confirm.body.actorKey,providerId:confirm.body.providerId,sessionId:confirm.body.sessionId,bootId:confirm.body.bootId,processBootId:confirm.body.processBootId,useTicketId:confirm.body.useTicketId,invokedAt:f.now()},commandId:"late-confirm"})).rejects.toThrow("MEMORY_RECALL_USE_UNKNOWN")});
it("forget before dispatch keeps no pending use and no invocation",async()=>{const f=fixture(),a=await f.active(),s=await f.assemble(a),p=await f.context.validateForDispatch(f.actor,s);await f.policy.act(f.actor,await f.policy.event(f.actor,{kind:"forget",nonce:randomUUID(),...ref(a)}));let calls=0;await expect(f.context.dispatch(f.actor,p,()=>{calls++;return "bad"})).rejects.toThrow("MEMORY_CONTEXT_STALE");expect(calls).toBe(0);expect(tickets(f)).toEqual([])});
it("current support invalidation before dispatch overrides recall state",async()=>{const f=fixture(),a=await f.active(),s=await f.assemble(a),p=await f.context.validateForDispatch(f.actor,s);await f.registry.prepareChange(f.access,f.provider.adapter,a.ref);let calls=0;await expect(f.context.dispatch(f.actor,p,()=>{calls++;return "bad"})).rejects.toThrow("MEMORY_CONTEXT_FACT_STALE");expect(calls).toBe(0);expect(tickets(f)).toEqual([])});
it("actual use invalidates a prior maintenance candidate without reviving truth",async()=>{const f=fixture(),a=await f.active();await f.recall.configure(f.actor,{...DEFAULT_RECALL_POLICY,version:"enabled",maintenanceMode:"enabled"});await f.recall.rank(f.actor);f.advance(90*86400000);const preview=await f.command("maintenancePreview",{requiredFactRefs:[]});const s=await f.assemble(a),p=await f.context.validateForDispatch(f.actor,s);await f.context.dispatch(f.actor,p,()=>"ok");await expect(f.command("commit",{preview},"stale-maintenance")).rejects.toThrow("MEMORY_RECALL_STALE");expect((await f.recall.rank(f.actor)).items).toHaveLength(1)});
it("use records and receipts contain metadata only",async()=>{const f=fixture(),a=await f.active(),s=await f.assemble(a),p=await f.context.validateForDispatch(f.actor,s);await f.context.dispatch(f.actor,p,()=>"ok");expect(JSON.stringify(tickets(f))).not.toContain("I prefer bash");expect(JSON.stringify(f.contextCommands)).not.toContain("I prefer bash");expect(tickets(f)[0].dependencies[0]).toMatchObject({...ref(a),visibilityRevision:0})});
it("worker rejects a snapshot with fact refs but omitted visibility dependencies",async()=>{const f=fixture(),a=await f.active();await f.assemble(a);const saved=f.contextCommands.find(c=>c.kind==="snapshot"),body={...saved.body,snapshotId:"forged-no-visibility"};delete body.recallDeps;await expect(f.transport.contextCommand({...saved,body,commandId:"without-visibility"})).rejects.toThrow("MEMORY_RECALL_VISIBILITY_STALE")});
it("archive restore during counting prevents a new snapshot with stale baseline",async()=>{const f=fixture(),a=await f.active();let changed=false;const counter={...f.options.counter,count:async(r:any)=>{if(!changed){changed=true;await action(f,a,"archive");await action(f,a,"restore")}return JSON.stringify(r.body).length}},context=createMainContext({...f.options,counter});await expect(context.assemble(f.actor,{sessionId:"session-a",sourceRefs:[],factRefs:[ref(a)]})).rejects.toThrow("MEMORY_RECALL_VISIBILITY_STALE")});
it("queued archive runs before final claim and prevents sender invocation",async()=>{const f=fixture(),a=await f.active(),s=await f.assemble(a),p=await f.context.validateForDispatch(f.actor,s),archive=await f.recall.preview(f.actor,[ref(a)],"archive");let calls=0;const archiving=f.recall.apply(f.actor,archive),sending=f.context.dispatch(f.actor,p,()=>{calls++;return "bad"});await archiving;await expect(sending).rejects.toThrow("MEMORY_RECALL_FACT_ARCHIVED");expect(calls).toBe(0)});
it("network result may remain pending while later archive executes without a resend",async()=>{const f=fixture(),a=await f.active(),s=await f.assemble(a),p=await f.context.validateForDispatch(f.actor,s);let finish!:(v:string)=>void,invoked!:()=>void,calls=0;const reached=new Promise<void>(r=>{invoked=r}),response=new Promise<string>(r=>{finish=r});const sending=f.context.dispatch(f.actor,p,()=>{calls++;invoked();return response});await reached;await action(f,a,"archive");finish("local-result");expect((await sending).status).toBe("sent");expect(calls).toBe(1);expect((await f.recall.metadata(f.actor,[ref(a)])).targets[0]).toMatchObject({visibility:"archived",accessCount:1})});
it("pending required use protects maintenance until recovery changes only ticket state",async()=>{const f=fixture(),a=await f.active();await f.recall.configure(f.actor,{...DEFAULT_RECALL_POLICY,version:"enabled",maintenanceMode:"enabled"});const transport={contextCommand:async(c:any)=>{const result=await f.options.transport.contextCommand(c);if(c.kind==="claim")throw new Error("MEMORY_WORKER_FAILED");return result}},context=createMainContext({...f.options,transport}),s=await context.assemble(f.actor,{sessionId:"session-a",sourceRefs:[],factRefs:[ref(a)]}),p=await context.validateForDispatch(f.actor,s);await expect(context.dispatch(f.actor,p,()=>"bad")).rejects.toThrow("MEMORY_WORKER_FAILED");f.advance(90*86400000);expect((await f.recall.maintain(f.actor)).archived).toBe(0);expect((await f.recall.metadata(f.actor,[ref(a)])).targets[0].lastAccessAt).toBeNull();const authority=createMainActorAuthority({resolveActor:()=>"actor-a"}),actor=authority.bindActor(f.access,f.provider.adapter,f.identity),next=createMainRecall({actorAuthority:authority,transport:f.transport});await next.recover(actor);expect((await next.maintain(actor)).archived).toBe(1);expect((await next.metadata(actor,[ref(a)])).targets[0]).toMatchObject({lastAccessAt:null,visibility:"archived"})});
it.each(["invalid","future","past"])("%s invocation clock fails before any sender call",async kind=>{const f=fixture(),a=await f.active(),clock=()=>kind==="invalid"?NaN:f.now()+(kind==="future"?1:-1)*86400000,context=createMainContext({...f.options,clock}),s=await context.assemble(f.actor,{sessionId:"session-a",sourceRefs:[],factRefs:[ref(a)]}),p=await context.validateForDispatch(f.actor,s);let calls=0;await expect(context.dispatch(f.actor,p,()=>{calls++;return "bad"})).rejects.toThrow("MEMORY_RECALL_CLOCK_INVALID");expect(calls).toBe(0);expect(tickets(f)).toEqual([])});
it("clock jump after durable claim prevents invocation and preserves unknown ticket",async()=>{const f=fixture(),a=await f.active();let reads=0;const clock=()=>f.now()+(reads++?86400000:0),context=createMainContext({...f.options,clock}),s=await context.assemble(f.actor,{sessionId:"session-a",sourceRefs:[],factRefs:[ref(a)]}),p=await context.validateForDispatch(f.actor,s);let calls=0;await expect(context.dispatch(f.actor,p,()=>{calls++;return "bad"})).rejects.toThrow("MEMORY_RECALL_CLOCK_INVALID");expect(calls).toBe(0);expect(tickets(f)[0].state).toBe("unknown");expect((await f.recall.metadata(f.actor,[ref(a)])).targets[0].lastAccessAt).toBeNull()});
